<?php
/**
 * BookIn
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Jiwa\Model;

use \ArrayAccess;
use \Jiwa\ObjectSerializer;

/**
 * BookIn Class Doc Comment
 *
 * @category Class
 * @description BookIn
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookIn implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BookIn';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'book_in_id' => 'string',
        'book_in_no' => 'string',
        'shipment' => '\Jiwa\Model\BookInShipment',
        'book_in_date' => '\DateTime',
        'activated' => 'bool',
        'gl_sets_rec_id' => 'string',
        'last_saved_date_time' => '\DateTime',
        'lines' => '\Jiwa\Model\BookInLine[]',
        'other_book_ins_for_this_shipment' => '\Jiwa\Model\BookInOtherBookIn[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'book_in_id' => null,
        'book_in_no' => null,
        'shipment' => null,
        'book_in_date' => 'date-time',
        'activated' => null,
        'gl_sets_rec_id' => null,
        'last_saved_date_time' => 'date-time',
        'lines' => null,
        'other_book_ins_for_this_shipment' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'book_in_id' => 'BookInID',
        'book_in_no' => 'BookInNo',
        'shipment' => 'Shipment',
        'book_in_date' => 'BookInDate',
        'activated' => 'Activated',
        'gl_sets_rec_id' => 'GL_Sets_RecID',
        'last_saved_date_time' => 'LastSavedDateTime',
        'lines' => 'Lines',
        'other_book_ins_for_this_shipment' => 'OtherBookInsForThisShipment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'book_in_id' => 'setBookInId',
        'book_in_no' => 'setBookInNo',
        'shipment' => 'setShipment',
        'book_in_date' => 'setBookInDate',
        'activated' => 'setActivated',
        'gl_sets_rec_id' => 'setGlSetsRecId',
        'last_saved_date_time' => 'setLastSavedDateTime',
        'lines' => 'setLines',
        'other_book_ins_for_this_shipment' => 'setOtherBookInsForThisShipment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'book_in_id' => 'getBookInId',
        'book_in_no' => 'getBookInNo',
        'shipment' => 'getShipment',
        'book_in_date' => 'getBookInDate',
        'activated' => 'getActivated',
        'gl_sets_rec_id' => 'getGlSetsRecId',
        'last_saved_date_time' => 'getLastSavedDateTime',
        'lines' => 'getLines',
        'other_book_ins_for_this_shipment' => 'getOtherBookInsForThisShipment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['book_in_id'] = isset($data['book_in_id']) ? $data['book_in_id'] : null;
        $this->container['book_in_no'] = isset($data['book_in_no']) ? $data['book_in_no'] : null;
        $this->container['shipment'] = isset($data['shipment']) ? $data['shipment'] : null;
        $this->container['book_in_date'] = isset($data['book_in_date']) ? $data['book_in_date'] : null;
        $this->container['activated'] = isset($data['activated']) ? $data['activated'] : null;
        $this->container['gl_sets_rec_id'] = isset($data['gl_sets_rec_id']) ? $data['gl_sets_rec_id'] : null;
        $this->container['last_saved_date_time'] = isset($data['last_saved_date_time']) ? $data['last_saved_date_time'] : null;
        $this->container['lines'] = isset($data['lines']) ? $data['lines'] : null;
        $this->container['other_book_ins_for_this_shipment'] = isset($data['other_book_ins_for_this_shipment']) ? $data['other_book_ins_for_this_shipment'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets book_in_id
     *
     * @return string
     */
    public function getBookInId()
    {
        return $this->container['book_in_id'];
    }

    /**
     * Sets book_in_id
     *
     * @param string $book_in_id book_in_id
     *
     * @return $this
     */
    public function setBookInId($book_in_id)
    {
        $this->container['book_in_id'] = $book_in_id;

        return $this;
    }

    /**
     * Gets book_in_no
     *
     * @return string
     */
    public function getBookInNo()
    {
        return $this->container['book_in_no'];
    }

    /**
     * Sets book_in_no
     *
     * @param string $book_in_no book_in_no
     *
     * @return $this
     */
    public function setBookInNo($book_in_no)
    {
        $this->container['book_in_no'] = $book_in_no;

        return $this;
    }

    /**
     * Gets shipment
     *
     * @return \Jiwa\Model\BookInShipment
     */
    public function getShipment()
    {
        return $this->container['shipment'];
    }

    /**
     * Sets shipment
     *
     * @param \Jiwa\Model\BookInShipment $shipment shipment
     *
     * @return $this
     */
    public function setShipment($shipment)
    {
        $this->container['shipment'] = $shipment;

        return $this;
    }

    /**
     * Gets book_in_date
     *
     * @return \DateTime
     */
    public function getBookInDate()
    {
        return $this->container['book_in_date'];
    }

    /**
     * Sets book_in_date
     *
     * @param \DateTime $book_in_date book_in_date
     *
     * @return $this
     */
    public function setBookInDate($book_in_date)
    {
        $this->container['book_in_date'] = $book_in_date;

        return $this;
    }

    /**
     * Gets activated
     *
     * @return bool
     */
    public function getActivated()
    {
        return $this->container['activated'];
    }

    /**
     * Sets activated
     *
     * @param bool $activated activated
     *
     * @return $this
     */
    public function setActivated($activated)
    {
        $this->container['activated'] = $activated;

        return $this;
    }

    /**
     * Gets gl_sets_rec_id
     *
     * @return string
     */
    public function getGlSetsRecId()
    {
        return $this->container['gl_sets_rec_id'];
    }

    /**
     * Sets gl_sets_rec_id
     *
     * @param string $gl_sets_rec_id gl_sets_rec_id
     *
     * @return $this
     */
    public function setGlSetsRecId($gl_sets_rec_id)
    {
        $this->container['gl_sets_rec_id'] = $gl_sets_rec_id;

        return $this;
    }

    /**
     * Gets last_saved_date_time
     *
     * @return \DateTime
     */
    public function getLastSavedDateTime()
    {
        return $this->container['last_saved_date_time'];
    }

    /**
     * Sets last_saved_date_time
     *
     * @param \DateTime $last_saved_date_time last_saved_date_time
     *
     * @return $this
     */
    public function setLastSavedDateTime($last_saved_date_time)
    {
        $this->container['last_saved_date_time'] = $last_saved_date_time;

        return $this;
    }

    /**
     * Gets lines
     *
     * @return \Jiwa\Model\BookInLine[]
     */
    public function getLines()
    {
        return $this->container['lines'];
    }

    /**
     * Sets lines
     *
     * @param \Jiwa\Model\BookInLine[] $lines lines
     *
     * @return $this
     */
    public function setLines($lines)
    {
        $this->container['lines'] = $lines;

        return $this;
    }

    /**
     * Gets other_book_ins_for_this_shipment
     *
     * @return \Jiwa\Model\BookInOtherBookIn[]
     */
    public function getOtherBookInsForThisShipment()
    {
        return $this->container['other_book_ins_for_this_shipment'];
    }

    /**
     * Sets other_book_ins_for_this_shipment
     *
     * @param \Jiwa\Model\BookInOtherBookIn[] $other_book_ins_for_this_shipment other_book_ins_for_this_shipment
     *
     * @return $this
     */
    public function setOtherBookInsForThisShipment($other_book_ins_for_this_shipment)
    {
        $this->container['other_book_ins_for_this_shipment'] = $other_book_ins_for_this_shipment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


