<?php
/**
 * WarehouseTransferInLineDetail
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Jiwa\JiwaModel;

use \ArrayAccess;
use \Jiwa\ObjectSerializer;

/**
 * WarehouseTransferInLineDetail Class Doc Comment
 *
 * @category Class
 * @description WarehouseTransferInLineDetail
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WarehouseTransferInLineDetail implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WarehouseTransferInLineDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'transfer_line_details_id' => 'string',
        'quantity' => 'double',
        'cost' => 'double',
        'source_serial_no' => 'string',
        'source_bin_location' => 'string',
        'source_expiry_date' => '\DateTime',
        'source_date_in' => '\DateTime',
        'source_special_price' => 'double',
        'source_in_sohid' => 'string',
        'in_transit_in_sohid' => 'string',
        'destination_in_sohid' => 'string',
        'quantity_received' => 'double',
        'cost_received' => 'double',
        'destination_serial_no' => 'string',
        'destination_bin_location' => 'string',
        'destination_expiry_date' => '\DateTime',
        'added_cost' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'transfer_line_details_id' => null,
        'quantity' => 'double',
        'cost' => 'double',
        'source_serial_no' => null,
        'source_bin_location' => null,
        'source_expiry_date' => 'date-time',
        'source_date_in' => 'date-time',
        'source_special_price' => 'double',
        'source_in_sohid' => null,
        'in_transit_in_sohid' => null,
        'destination_in_sohid' => null,
        'quantity_received' => 'double',
        'cost_received' => 'double',
        'destination_serial_no' => null,
        'destination_bin_location' => null,
        'destination_expiry_date' => 'date-time',
        'added_cost' => 'double'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transfer_line_details_id' => 'TransferLineDetailsID',
        'quantity' => 'Quantity',
        'cost' => 'Cost',
        'source_serial_no' => 'SourceSerialNo',
        'source_bin_location' => 'SourceBinLocation',
        'source_expiry_date' => 'SourceExpiryDate',
        'source_date_in' => 'SourceDateIn',
        'source_special_price' => 'SourceSpecialPrice',
        'source_in_sohid' => 'Source_IN_SOHID',
        'in_transit_in_sohid' => 'InTransit_IN_SOHID',
        'destination_in_sohid' => 'Destination_IN_SOHID',
        'quantity_received' => 'QuantityReceived',
        'cost_received' => 'CostReceived',
        'destination_serial_no' => 'DestinationSerialNo',
        'destination_bin_location' => 'DestinationBinLocation',
        'destination_expiry_date' => 'DestinationExpiryDate',
        'added_cost' => 'AddedCost'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transfer_line_details_id' => 'setTransferLineDetailsId',
        'quantity' => 'setQuantity',
        'cost' => 'setCost',
        'source_serial_no' => 'setSourceSerialNo',
        'source_bin_location' => 'setSourceBinLocation',
        'source_expiry_date' => 'setSourceExpiryDate',
        'source_date_in' => 'setSourceDateIn',
        'source_special_price' => 'setSourceSpecialPrice',
        'source_in_sohid' => 'setSourceInSohid',
        'in_transit_in_sohid' => 'setInTransitInSohid',
        'destination_in_sohid' => 'setDestinationInSohid',
        'quantity_received' => 'setQuantityReceived',
        'cost_received' => 'setCostReceived',
        'destination_serial_no' => 'setDestinationSerialNo',
        'destination_bin_location' => 'setDestinationBinLocation',
        'destination_expiry_date' => 'setDestinationExpiryDate',
        'added_cost' => 'setAddedCost'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transfer_line_details_id' => 'getTransferLineDetailsId',
        'quantity' => 'getQuantity',
        'cost' => 'getCost',
        'source_serial_no' => 'getSourceSerialNo',
        'source_bin_location' => 'getSourceBinLocation',
        'source_expiry_date' => 'getSourceExpiryDate',
        'source_date_in' => 'getSourceDateIn',
        'source_special_price' => 'getSourceSpecialPrice',
        'source_in_sohid' => 'getSourceInSohid',
        'in_transit_in_sohid' => 'getInTransitInSohid',
        'destination_in_sohid' => 'getDestinationInSohid',
        'quantity_received' => 'getQuantityReceived',
        'cost_received' => 'getCostReceived',
        'destination_serial_no' => 'getDestinationSerialNo',
        'destination_bin_location' => 'getDestinationBinLocation',
        'destination_expiry_date' => 'getDestinationExpiryDate',
        'added_cost' => 'getAddedCost'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['transfer_line_details_id'] = isset($data['transfer_line_details_id']) ? $data['transfer_line_details_id'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['cost'] = isset($data['cost']) ? $data['cost'] : null;
        $this->container['source_serial_no'] = isset($data['source_serial_no']) ? $data['source_serial_no'] : null;
        $this->container['source_bin_location'] = isset($data['source_bin_location']) ? $data['source_bin_location'] : null;
        $this->container['source_expiry_date'] = isset($data['source_expiry_date']) ? $data['source_expiry_date'] : null;
        $this->container['source_date_in'] = isset($data['source_date_in']) ? $data['source_date_in'] : null;
        $this->container['source_special_price'] = isset($data['source_special_price']) ? $data['source_special_price'] : null;
        $this->container['source_in_sohid'] = isset($data['source_in_sohid']) ? $data['source_in_sohid'] : null;
        $this->container['in_transit_in_sohid'] = isset($data['in_transit_in_sohid']) ? $data['in_transit_in_sohid'] : null;
        $this->container['destination_in_sohid'] = isset($data['destination_in_sohid']) ? $data['destination_in_sohid'] : null;
        $this->container['quantity_received'] = isset($data['quantity_received']) ? $data['quantity_received'] : null;
        $this->container['cost_received'] = isset($data['cost_received']) ? $data['cost_received'] : null;
        $this->container['destination_serial_no'] = isset($data['destination_serial_no']) ? $data['destination_serial_no'] : null;
        $this->container['destination_bin_location'] = isset($data['destination_bin_location']) ? $data['destination_bin_location'] : null;
        $this->container['destination_expiry_date'] = isset($data['destination_expiry_date']) ? $data['destination_expiry_date'] : null;
        $this->container['added_cost'] = isset($data['added_cost']) ? $data['added_cost'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transfer_line_details_id
     *
     * @return string
     */
    public function getTransferLineDetailsId()
    {
        return $this->container['transfer_line_details_id'];
    }

    /**
     * Sets transfer_line_details_id
     *
     * @param string $transfer_line_details_id transfer_line_details_id
     *
     * @return $this
     */
    public function setTransferLineDetailsId($transfer_line_details_id)
    {
        $this->container['transfer_line_details_id'] = $transfer_line_details_id;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return double
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param double $quantity quantity
     *
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return double
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param double $cost cost
     *
     * @return $this
     */
    public function setCost($cost)
    {
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets source_serial_no
     *
     * @return string
     */
    public function getSourceSerialNo()
    {
        return $this->container['source_serial_no'];
    }

    /**
     * Sets source_serial_no
     *
     * @param string $source_serial_no source_serial_no
     *
     * @return $this
     */
    public function setSourceSerialNo($source_serial_no)
    {
        $this->container['source_serial_no'] = $source_serial_no;

        return $this;
    }

    /**
     * Gets source_bin_location
     *
     * @return string
     */
    public function getSourceBinLocation()
    {
        return $this->container['source_bin_location'];
    }

    /**
     * Sets source_bin_location
     *
     * @param string $source_bin_location source_bin_location
     *
     * @return $this
     */
    public function setSourceBinLocation($source_bin_location)
    {
        $this->container['source_bin_location'] = $source_bin_location;

        return $this;
    }

    /**
     * Gets source_expiry_date
     *
     * @return \DateTime
     */
    public function getSourceExpiryDate()
    {
        return $this->container['source_expiry_date'];
    }

    /**
     * Sets source_expiry_date
     *
     * @param \DateTime $source_expiry_date source_expiry_date
     *
     * @return $this
     */
    public function setSourceExpiryDate($source_expiry_date)
    {
        $this->container['source_expiry_date'] = $source_expiry_date;

        return $this;
    }

    /**
     * Gets source_date_in
     *
     * @return \DateTime
     */
    public function getSourceDateIn()
    {
        return $this->container['source_date_in'];
    }

    /**
     * Sets source_date_in
     *
     * @param \DateTime $source_date_in source_date_in
     *
     * @return $this
     */
    public function setSourceDateIn($source_date_in)
    {
        $this->container['source_date_in'] = $source_date_in;

        return $this;
    }

    /**
     * Gets source_special_price
     *
     * @return double
     */
    public function getSourceSpecialPrice()
    {
        return $this->container['source_special_price'];
    }

    /**
     * Sets source_special_price
     *
     * @param double $source_special_price source_special_price
     *
     * @return $this
     */
    public function setSourceSpecialPrice($source_special_price)
    {
        $this->container['source_special_price'] = $source_special_price;

        return $this;
    }

    /**
     * Gets source_in_sohid
     *
     * @return string
     */
    public function getSourceInSohid()
    {
        return $this->container['source_in_sohid'];
    }

    /**
     * Sets source_in_sohid
     *
     * @param string $source_in_sohid source_in_sohid
     *
     * @return $this
     */
    public function setSourceInSohid($source_in_sohid)
    {
        $this->container['source_in_sohid'] = $source_in_sohid;

        return $this;
    }

    /**
     * Gets in_transit_in_sohid
     *
     * @return string
     */
    public function getInTransitInSohid()
    {
        return $this->container['in_transit_in_sohid'];
    }

    /**
     * Sets in_transit_in_sohid
     *
     * @param string $in_transit_in_sohid in_transit_in_sohid
     *
     * @return $this
     */
    public function setInTransitInSohid($in_transit_in_sohid)
    {
        $this->container['in_transit_in_sohid'] = $in_transit_in_sohid;

        return $this;
    }

    /**
     * Gets destination_in_sohid
     *
     * @return string
     */
    public function getDestinationInSohid()
    {
        return $this->container['destination_in_sohid'];
    }

    /**
     * Sets destination_in_sohid
     *
     * @param string $destination_in_sohid destination_in_sohid
     *
     * @return $this
     */
    public function setDestinationInSohid($destination_in_sohid)
    {
        $this->container['destination_in_sohid'] = $destination_in_sohid;

        return $this;
    }

    /**
     * Gets quantity_received
     *
     * @return double
     */
    public function getQuantityReceived()
    {
        return $this->container['quantity_received'];
    }

    /**
     * Sets quantity_received
     *
     * @param double $quantity_received quantity_received
     *
     * @return $this
     */
    public function setQuantityReceived($quantity_received)
    {
        $this->container['quantity_received'] = $quantity_received;

        return $this;
    }

    /**
     * Gets cost_received
     *
     * @return double
     */
    public function getCostReceived()
    {
        return $this->container['cost_received'];
    }

    /**
     * Sets cost_received
     *
     * @param double $cost_received cost_received
     *
     * @return $this
     */
    public function setCostReceived($cost_received)
    {
        $this->container['cost_received'] = $cost_received;

        return $this;
    }

    /**
     * Gets destination_serial_no
     *
     * @return string
     */
    public function getDestinationSerialNo()
    {
        return $this->container['destination_serial_no'];
    }

    /**
     * Sets destination_serial_no
     *
     * @param string $destination_serial_no destination_serial_no
     *
     * @return $this
     */
    public function setDestinationSerialNo($destination_serial_no)
    {
        $this->container['destination_serial_no'] = $destination_serial_no;

        return $this;
    }

    /**
     * Gets destination_bin_location
     *
     * @return string
     */
    public function getDestinationBinLocation()
    {
        return $this->container['destination_bin_location'];
    }

    /**
     * Sets destination_bin_location
     *
     * @param string $destination_bin_location destination_bin_location
     *
     * @return $this
     */
    public function setDestinationBinLocation($destination_bin_location)
    {
        $this->container['destination_bin_location'] = $destination_bin_location;

        return $this;
    }

    /**
     * Gets destination_expiry_date
     *
     * @return \DateTime
     */
    public function getDestinationExpiryDate()
    {
        return $this->container['destination_expiry_date'];
    }

    /**
     * Sets destination_expiry_date
     *
     * @param \DateTime $destination_expiry_date destination_expiry_date
     *
     * @return $this
     */
    public function setDestinationExpiryDate($destination_expiry_date)
    {
        $this->container['destination_expiry_date'] = $destination_expiry_date;

        return $this;
    }

    /**
     * Gets added_cost
     *
     * @return double
     */
    public function getAddedCost()
    {
        return $this->container['added_cost'];
    }

    /**
     * Sets added_cost
     *
     * @param double $added_cost added_cost
     *
     * @return $this
     */
    public function setAddedCost($added_cost)
    {
        $this->container['added_cost'] = $added_cost;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


