<?php
/**
 * BillPATCHRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * BillPATCHRequestTest Class Doc Comment
 *
 * @category    Class
 * @description BillPATCHRequest
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BillPATCHRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BillPATCHRequest"
     */
    public function testBillPATCHRequest()
    {
    }

    /**
     * Test attribute "bill_id"
     */
    public function testPropertyBillId()
    {
    }

    /**
     * Test attribute "bill_no"
     */
    public function testPropertyBillNo()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "is_enabled"
     */
    public function testPropertyIsEnabled()
    {
    }

    /**
     * Test attribute "maximum_production_capability"
     */
    public function testPropertyMaximumProductionCapability()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "row_hash"
     */
    public function testPropertyRowHash()
    {
    }

    /**
     * Test attribute "stages"
     */
    public function testPropertyStages()
    {
    }

    /**
     * Test attribute "outputs"
     */
    public function testPropertyOutputs()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "production_line"
     */
    public function testPropertyProductionLine()
    {
    }

    /**
     * Test attribute "bill_parents"
     */
    public function testPropertyBillParents()
    {
    }
}
