<?php
/**
 * CreditTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * CreditTest Class Doc Comment
 *
 * @category    Class
 * @description Credit
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreditTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Credit"
     */
    public function testCredit()
    {
    }

    /**
     * Test attribute "rec_id"
     */
    public function testPropertyRecId()
    {
    }

    /**
     * Test attribute "credit_no"
     */
    public function testPropertyCreditNo()
    {
    }

    /**
     * Test attribute "creditor_ref"
     */
    public function testPropertyCreditorRef()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "credit_date"
     */
    public function testPropertyCreditDate()
    {
    }

    /**
     * Test attribute "creditor_id"
     */
    public function testPropertyCreditorId()
    {
    }

    /**
     * Test attribute "creditor_account_no"
     */
    public function testPropertyCreditorAccountNo()
    {
    }

    /**
     * Test attribute "creditor_name"
     */
    public function testPropertyCreditorName()
    {
    }

    /**
     * Test attribute "row_hash"
     */
    public function testPropertyRowHash()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }

    /**
     * Test attribute "shippings"
     */
    public function testPropertyShippings()
    {
    }

    /**
     * Test attribute "purchase_orders"
     */
    public function testPropertyPurchaseOrders()
    {
    }
}
