<?php
/**
 * CurrencyRatePATCHRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * CurrencyRatePATCHRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CurrencyRatePATCHRequest
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CurrencyRatePATCHRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CurrencyRatePATCHRequest"
     */
    public function testCurrencyRatePATCHRequest()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "rate_id"
     */
    public function testPropertyRateId()
    {
    }

    /**
     * Test attribute "date_entered"
     */
    public function testPropertyDateEntered()
    {
    }

    /**
     * Test attribute "effective_date"
     */
    public function testPropertyEffectiveDate()
    {
    }

    /**
     * Test attribute "effective_date_end"
     */
    public function testPropertyEffectiveDateEnd()
    {
    }

    /**
     * Test attribute "transaction_rate"
     */
    public function testPropertyTransactionRate()
    {
    }
}
