<?php
/**
 * DBMainTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * DBMainTest Class Doc Comment
 *
 * @category    Class
 * @description DB_Main
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DBMainTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DBMain"
     */
    public function testDBMain()
    {
    }

    /**
     * Test attribute "debtor_id"
     */
    public function testPropertyDebtorId()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "account_no"
     */
    public function testPropertyAccountNo()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {
    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "address3"
     */
    public function testPropertyAddress3()
    {
    }

    /**
     * Test attribute "address4"
     */
    public function testPropertyAddress4()
    {
    }

    /**
     * Test attribute "post_code"
     */
    public function testPropertyPostCode()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "bank_name"
     */
    public function testPropertyBankName()
    {
    }

    /**
     * Test attribute "bank_acc"
     */
    public function testPropertyBankAcc()
    {
    }

    /**
     * Test attribute "bsbn"
     */
    public function testPropertyBsbn()
    {
    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {
    }

    /**
     * Test attribute "tax_exempt_no"
     */
    public function testPropertyTaxExemptNo()
    {
    }

    /**
     * Test attribute "credit_limit"
     */
    public function testPropertyCreditLimit()
    {
    }

    /**
     * Test attribute "early_pay_dis_on_stats_days"
     */
    public function testPropertyEarlyPayDisOnStatsDays()
    {
    }

    /**
     * Test attribute "early_pay_dis_on_stats_amt"
     */
    public function testPropertyEarlyPayDisOnStatsAmt()
    {
    }

    /**
     * Test attribute "last_purchase_date"
     */
    public function testPropertyLastPurchaseDate()
    {
    }

    /**
     * Test attribute "last_payment_date"
     */
    public function testPropertyLastPaymentDate()
    {
    }

    /**
     * Test attribute "standing_dis_on_invoices"
     */
    public function testPropertyStandingDisOnInvoices()
    {
    }

    /**
     * Test attribute "classification_id"
     */
    public function testPropertyClassificationId()
    {
    }

    /**
     * Test attribute "account_on_hold"
     */
    public function testPropertyAccountOnHold()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "current_balance"
     */
    public function testPropertyCurrentBalance()
    {
    }

    /**
     * Test attribute "period1"
     */
    public function testPropertyPeriod1()
    {
    }

    /**
     * Test attribute "period2"
     */
    public function testPropertyPeriod2()
    {
    }

    /**
     * Test attribute "period3"
     */
    public function testPropertyPeriod3()
    {
    }

    /**
     * Test attribute "period4"
     */
    public function testPropertyPeriod4()
    {
    }

    /**
     * Test attribute "alt_account_no"
     */
    public function testPropertyAltAccountNo()
    {
    }

    /**
     * Test attribute "notify_required"
     */
    public function testPropertyNotifyRequired()
    {
    }

    /**
     * Test attribute "notify_address"
     */
    public function testPropertyNotifyAddress()
    {
    }

    /**
     * Test attribute "commence_date"
     */
    public function testPropertyCommenceDate()
    {
    }

    /**
     * Test attribute "web_access"
     */
    public function testPropertyWebAccess()
    {
    }

    /**
     * Test attribute "parent_debtor_id"
     */
    public function testPropertyParentDebtorId()
    {
    }

    /**
     * Test attribute "alloc_last_saved_date_time"
     */
    public function testPropertyAllocLastSavedDateTime()
    {
    }

    /**
     * Test attribute "price_scheme_id"
     */
    public function testPropertyPriceSchemeId()
    {
    }

    /**
     * Test attribute "aust_post_dpid"
     */
    public function testPropertyAustPostDpid()
    {
    }

    /**
     * Test attribute "aust_post_bcsp"
     */
    public function testPropertyAustPostBcsp()
    {
    }

    /**
     * Test attribute "trading_name"
     */
    public function testPropertyTradingName()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "acn"
     */
    public function testPropertyAcn()
    {
    }

    /**
     * Test attribute "proprietors_name"
     */
    public function testPropertyProprietorsName()
    {
    }

    /**
     * Test attribute "fax_header"
     */
    public function testPropertyFaxHeader()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_control"
     */
    public function testPropertyLedgerIdDebtorControl()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_sales"
     */
    public function testPropertyLedgerIdDebtorSales()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_discounts"
     */
    public function testPropertyLedgerIdDebtorDiscounts()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_sourced_invoices"
     */
    public function testPropertyLedgerIdDebtorSourcedInvoices()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_debit_adjustment"
     */
    public function testPropertyLedgerIdDebtorDebitAdjustment()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_sourced_receipts"
     */
    public function testPropertyLedgerIdDebtorSourcedReceipts()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_credit_adjustment"
     */
    public function testPropertyLedgerIdDebtorCreditAdjustment()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_freight"
     */
    public function testPropertyLedgerIdDebtorFreight()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_insurance"
     */
    public function testPropertyLedgerIdDebtorInsurance()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_realised_gain_loss"
     */
    public function testPropertyLedgerIdDebtorRealisedGainLoss()
    {
    }

    /**
     * Test attribute "ledger_id_debtor_un_realised_gain_loss"
     */
    public function testPropertyLedgerIdDebtorUnRealisedGainLoss()
    {
    }

    /**
     * Test attribute "period_type"
     */
    public function testPropertyPeriodType()
    {
    }

    /**
     * Test attribute "terms_days"
     */
    public function testPropertyTermsDays()
    {
    }

    /**
     * Test attribute "terms_type"
     */
    public function testPropertyTermsType()
    {
    }

    /**
     * Test attribute "abn"
     */
    public function testPropertyAbn()
    {
    }

    /**
     * Test attribute "exclude_from_aging"
     */
    public function testPropertyExcludeFromAging()
    {
    }

    /**
     * Test attribute "b_pay_reference"
     */
    public function testPropertyBPayReference()
    {
    }

    /**
     * Test attribute "uses_fx"
     */
    public function testPropertyUsesFx()
    {
    }

    /**
     * Test attribute "fx_currency_id"
     */
    public function testPropertyFxCurrencyId()
    {
    }

    /**
     * Test attribute "fx_current_balance"
     */
    public function testPropertyFxCurrentBalance()
    {
    }

    /**
     * Test attribute "fx_period1"
     */
    public function testPropertyFxPeriod1()
    {
    }

    /**
     * Test attribute "fx_period2"
     */
    public function testPropertyFxPeriod2()
    {
    }

    /**
     * Test attribute "fx_period3"
     */
    public function testPropertyFxPeriod3()
    {
    }

    /**
     * Test attribute "fx_period4"
     */
    public function testPropertyFxPeriod4()
    {
    }

    /**
     * Test attribute "trading_status"
     */
    public function testPropertyTradingStatus()
    {
    }

    /**
     * Test attribute "category1_id"
     */
    public function testPropertyCategory1Id()
    {
    }

    /**
     * Test attribute "category2_id"
     */
    public function testPropertyCategory2Id()
    {
    }

    /**
     * Test attribute "category3_id"
     */
    public function testPropertyCategory3Id()
    {
    }

    /**
     * Test attribute "category4_id"
     */
    public function testPropertyCategory4Id()
    {
    }

    /**
     * Test attribute "category5_id"
     */
    public function testPropertyCategory5Id()
    {
    }

    /**
     * Test attribute "bo_priorities_rec_id"
     */
    public function testPropertyBoPrioritiesRecId()
    {
    }

    /**
     * Test attribute "pricing_group_id"
     */
    public function testPropertyPricingGroupId()
    {
    }

    /**
     * Test attribute "budgeted_gp_percentage"
     */
    public function testPropertyBudgetedGpPercentage()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "fr_carriers_rec_id"
     */
    public function testPropertyFrCarriersRecId()
    {
    }

    /**
     * Test attribute "fr_carrier_services_rec_id"
     */
    public function testPropertyFrCarrierServicesRecId()
    {
    }

    /**
     * Test attribute "carrier_account_no"
     */
    public function testPropertyCarrierAccountNo()
    {
    }

    /**
     * Test attribute "charge_to"
     */
    public function testPropertyChargeTo()
    {
    }

    /**
     * Test attribute "is_cash_only"
     */
    public function testPropertyIsCashOnly()
    {
    }
}
