<?php
/**
 * DebtorSystemTemplateFieldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * DebtorSystemTemplateFieldTest Class Doc Comment
 *
 * @category    Class
 * @description DebtorSystemTemplateField
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DebtorSystemTemplateFieldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DebtorSystemTemplateField"
     */
    public function testDebtorSystemTemplateField()
    {
    }

    /**
     * Test attribute "field_type"
     */
    public function testPropertyFieldType()
    {
    }

    /**
     * Test attribute "line_number"
     */
    public function testPropertyLineNumber()
    {
    }

    /**
     * Test attribute "system_template_field_id"
     */
    public function testPropertySystemTemplateFieldId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "combo_text"
     */
    public function testPropertyComboText()
    {
    }

    /**
     * Test attribute "script_format_cell"
     */
    public function testPropertyScriptFormatCell()
    {
    }

    /**
     * Test attribute "script_button_clicked"
     */
    public function testPropertyScriptButtonClicked()
    {
    }

    /**
     * Test attribute "script_read_data"
     */
    public function testPropertyScriptReadData()
    {
    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {
    }

    /**
     * Test attribute "grid_handler_code"
     */
    public function testPropertyGridHandlerCode()
    {
    }
}
