<?php
/**
 * DebtorPATCHRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * DebtorPATCHRequestTest Class Doc Comment
 *
 * @category    Class
 * @description DebtorPATCHRequest
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DebtorPATCHRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DebtorPATCHRequest"
     */
    public function testDebtorPATCHRequest()
    {
    }

    /**
     * Test attribute "debtor_id"
     */
    public function testPropertyDebtorId()
    {
    }

    /**
     * Test attribute "credit_limit"
     */
    public function testPropertyCreditLimit()
    {
    }

    /**
     * Test attribute "early_payment_discount_days"
     */
    public function testPropertyEarlyPaymentDiscountDays()
    {
    }

    /**
     * Test attribute "early_payment_discount_amount"
     */
    public function testPropertyEarlyPaymentDiscountAmount()
    {
    }

    /**
     * Test attribute "last_purchase_date"
     */
    public function testPropertyLastPurchaseDate()
    {
    }

    /**
     * Test attribute "last_payment_date"
     */
    public function testPropertyLastPaymentDate()
    {
    }

    /**
     * Test attribute "standing_discount_on_invoices"
     */
    public function testPropertyStandingDiscountOnInvoices()
    {
    }

    /**
     * Test attribute "account_on_hold"
     */
    public function testPropertyAccountOnHold()
    {
    }

    /**
     * Test attribute "current_balance"
     */
    public function testPropertyCurrentBalance()
    {
    }

    /**
     * Test attribute "period1_balance"
     */
    public function testPropertyPeriod1Balance()
    {
    }

    /**
     * Test attribute "period2_balance"
     */
    public function testPropertyPeriod2Balance()
    {
    }

    /**
     * Test attribute "period3_balance"
     */
    public function testPropertyPeriod3Balance()
    {
    }

    /**
     * Test attribute "period4_balance"
     */
    public function testPropertyPeriod4Balance()
    {
    }

    /**
     * Test attribute "fx_current_balance"
     */
    public function testPropertyFxCurrentBalance()
    {
    }

    /**
     * Test attribute "fx_period1_balance"
     */
    public function testPropertyFxPeriod1Balance()
    {
    }

    /**
     * Test attribute "fx_period2_balance"
     */
    public function testPropertyFxPeriod2Balance()
    {
    }

    /**
     * Test attribute "fx_period3_balance"
     */
    public function testPropertyFxPeriod3Balance()
    {
    }

    /**
     * Test attribute "fx_period4_balance"
     */
    public function testPropertyFxPeriod4Balance()
    {
    }

    /**
     * Test attribute "notify_required"
     */
    public function testPropertyNotifyRequired()
    {
    }

    /**
     * Test attribute "web_access"
     */
    public function testPropertyWebAccess()
    {
    }

    /**
     * Test attribute "commence_date"
     */
    public function testPropertyCommenceDate()
    {
    }

    /**
     * Test attribute "trading_status"
     */
    public function testPropertyTradingStatus()
    {
    }

    /**
     * Test attribute "period_type"
     */
    public function testPropertyPeriodType()
    {
    }

    /**
     * Test attribute "uses_fx"
     */
    public function testPropertyUsesFx()
    {
    }

    /**
     * Test attribute "is_cash_only"
     */
    public function testPropertyIsCashOnly()
    {
    }

    /**
     * Test attribute "terms_days"
     */
    public function testPropertyTermsDays()
    {
    }

    /**
     * Test attribute "terms_type"
     */
    public function testPropertyTermsType()
    {
    }

    /**
     * Test attribute "exclude_from_aging"
     */
    public function testPropertyExcludeFromAging()
    {
    }

    /**
     * Test attribute "debtor_is_branch_account"
     */
    public function testPropertyDebtorIsBranchAccount()
    {
    }

    /**
     * Test attribute "remaining_normal_prepaid_labour_pack_hours"
     */
    public function testPropertyRemainingNormalPrepaidLabourPackHours()
    {
    }

    /**
     * Test attribute "remaining_special_prepaid_labour_pack_hours"
     */
    public function testPropertyRemainingSpecialPrepaidLabourPackHours()
    {
    }

    /**
     * Test attribute "fx_decimal_places"
     */
    public function testPropertyFxDecimalPlaces()
    {
    }

    /**
     * Test attribute "prospect_id"
     */
    public function testPropertyProspectId()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "account_no"
     */
    public function testPropertyAccountNo()
    {
    }

    /**
     * Test attribute "alt_account_no"
     */
    public function testPropertyAltAccountNo()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {
    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "address3"
     */
    public function testPropertyAddress3()
    {
    }

    /**
     * Test attribute "address4"
     */
    public function testPropertyAddress4()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "acn"
     */
    public function testPropertyAcn()
    {
    }

    /**
     * Test attribute "abn"
     */
    public function testPropertyAbn()
    {
    }

    /**
     * Test attribute "aust_post_dpid"
     */
    public function testPropertyAustPostDpid()
    {
    }

    /**
     * Test attribute "aust_post_bcsp"
     */
    public function testPropertyAustPostBcsp()
    {
    }

    /**
     * Test attribute "bank_name"
     */
    public function testPropertyBankName()
    {
    }

    /**
     * Test attribute "bank_account_no"
     */
    public function testPropertyBankAccountNo()
    {
    }

    /**
     * Test attribute "bank_bsbn"
     */
    public function testPropertyBankBsbn()
    {
    }

    /**
     * Test attribute "bank_account_name"
     */
    public function testPropertyBankAccountName()
    {
    }

    /**
     * Test attribute "tax_exemption_no"
     */
    public function testPropertyTaxExemptionNo()
    {
    }

    /**
     * Test attribute "notify_address"
     */
    public function testPropertyNotifyAddress()
    {
    }

    /**
     * Test attribute "parent_debtor_id"
     */
    public function testPropertyParentDebtorId()
    {
    }

    /**
     * Test attribute "parent_debtor_account_no"
     */
    public function testPropertyParentDebtorAccountNo()
    {
    }

    /**
     * Test attribute "parent_debtor_name"
     */
    public function testPropertyParentDebtorName()
    {
    }

    /**
     * Test attribute "price_scheme_id"
     */
    public function testPropertyPriceSchemeId()
    {
    }

    /**
     * Test attribute "price_scheme_description"
     */
    public function testPropertyPriceSchemeDescription()
    {
    }

    /**
     * Test attribute "trading_name"
     */
    public function testPropertyTradingName()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "proprietors_name"
     */
    public function testPropertyProprietorsName()
    {
    }

    /**
     * Test attribute "fax_header"
     */
    public function testPropertyFaxHeader()
    {
    }

    /**
     * Test attribute "fxid"
     */
    public function testPropertyFxid()
    {
    }

    /**
     * Test attribute "fx_name"
     */
    public function testPropertyFxName()
    {
    }

    /**
     * Test attribute "fx_short_name"
     */
    public function testPropertyFxShortName()
    {
    }

    /**
     * Test attribute "b_pay_reference"
     */
    public function testPropertyBPayReference()
    {
    }

    /**
     * Test attribute "classification"
     */
    public function testPropertyClassification()
    {
    }

    /**
     * Test attribute "category1"
     */
    public function testPropertyCategory1()
    {
    }

    /**
     * Test attribute "category2"
     */
    public function testPropertyCategory2()
    {
    }

    /**
     * Test attribute "category3"
     */
    public function testPropertyCategory3()
    {
    }

    /**
     * Test attribute "category4"
     */
    public function testPropertyCategory4()
    {
    }

    /**
     * Test attribute "category5"
     */
    public function testPropertyCategory5()
    {
    }

    /**
     * Test attribute "contact_names"
     */
    public function testPropertyContactNames()
    {
    }

    /**
     * Test attribute "group_memberships"
     */
    public function testPropertyGroupMemberships()
    {
    }

    /**
     * Test attribute "branch_debtors"
     */
    public function testPropertyBranchDebtors()
    {
    }

    /**
     * Test attribute "delivery_addresses"
     */
    public function testPropertyDeliveryAddresses()
    {
    }

    /**
     * Test attribute "freight_forwarder_addresses"
     */
    public function testPropertyFreightForwarderAddresses()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "credit_notes"
     */
    public function testPropertyCreditNotes()
    {
    }

    /**
     * Test attribute "directors"
     */
    public function testPropertyDirectors()
    {
    }

    /**
     * Test attribute "budgets"
     */
    public function testPropertyBudgets()
    {
    }

    /**
     * Test attribute "debtor_part_numbers"
     */
    public function testPropertyDebtorPartNumbers()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "debtor_systems"
     */
    public function testPropertyDebtorSystems()
    {
    }

    /**
     * Test attribute "debtor_ledgers"
     */
    public function testPropertyDebtorLedgers()
    {
    }
}
