<?php
/**
 * INClassificationQueryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * INClassificationQueryTest Class Doc Comment
 *
 * @category    Class
 * @description IN_ClassificationQuery
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class INClassificationQueryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "INClassificationQuery"
     */
    public function testINClassificationQuery()
    {
    }

    /**
     * Test attribute "inventory_classification_id"
     */
    public function testPropertyInventoryClassificationId()
    {
    }

    /**
     * Test attribute "inventory_classification_id_starts_with"
     */
    public function testPropertyInventoryClassificationIdStartsWith()
    {
    }

    /**
     * Test attribute "inventory_classification_id_ends_with"
     */
    public function testPropertyInventoryClassificationIdEndsWith()
    {
    }

    /**
     * Test attribute "inventory_classification_id_contains"
     */
    public function testPropertyInventoryClassificationIdContains()
    {
    }

    /**
     * Test attribute "inventory_classification_id_like"
     */
    public function testPropertyInventoryClassificationIdLike()
    {
    }

    /**
     * Test attribute "inventory_classification_id_between"
     */
    public function testPropertyInventoryClassificationIdBetween()
    {
    }

    /**
     * Test attribute "inventory_classification_id_in"
     */
    public function testPropertyInventoryClassificationIdIn()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "description_starts_with"
     */
    public function testPropertyDescriptionStartsWith()
    {
    }

    /**
     * Test attribute "description_ends_with"
     */
    public function testPropertyDescriptionEndsWith()
    {
    }

    /**
     * Test attribute "description_contains"
     */
    public function testPropertyDescriptionContains()
    {
    }

    /**
     * Test attribute "description_like"
     */
    public function testPropertyDescriptionLike()
    {
    }

    /**
     * Test attribute "description_between"
     */
    public function testPropertyDescriptionBetween()
    {
    }

    /**
     * Test attribute "description_in"
     */
    public function testPropertyDescriptionIn()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "last_saved_date_time_greater_than_or_equal_to"
     */
    public function testPropertyLastSavedDateTimeGreaterThanOrEqualTo()
    {
    }

    /**
     * Test attribute "last_saved_date_time_greater_than"
     */
    public function testPropertyLastSavedDateTimeGreaterThan()
    {
    }

    /**
     * Test attribute "last_saved_date_time_less_than"
     */
    public function testPropertyLastSavedDateTimeLessThan()
    {
    }

    /**
     * Test attribute "last_saved_date_time_less_than_or_equal_to"
     */
    public function testPropertyLastSavedDateTimeLessThanOrEqualTo()
    {
    }

    /**
     * Test attribute "last_saved_date_time_not_equal_to"
     */
    public function testPropertyLastSavedDateTimeNotEqualTo()
    {
    }

    /**
     * Test attribute "last_saved_date_time_between"
     */
    public function testPropertyLastSavedDateTimeBetween()
    {
    }

    /**
     * Test attribute "last_saved_date_time_in"
     */
    public function testPropertyLastSavedDateTimeIn()
    {
    }

    /**
     * Test attribute "ledger_inv_value"
     */
    public function testPropertyLedgerInvValue()
    {
    }

    /**
     * Test attribute "ledger_inv_value_starts_with"
     */
    public function testPropertyLedgerInvValueStartsWith()
    {
    }

    /**
     * Test attribute "ledger_inv_value_ends_with"
     */
    public function testPropertyLedgerInvValueEndsWith()
    {
    }

    /**
     * Test attribute "ledger_inv_value_contains"
     */
    public function testPropertyLedgerInvValueContains()
    {
    }

    /**
     * Test attribute "ledger_inv_value_like"
     */
    public function testPropertyLedgerInvValueLike()
    {
    }

    /**
     * Test attribute "ledger_inv_value_between"
     */
    public function testPropertyLedgerInvValueBetween()
    {
    }

    /**
     * Test attribute "ledger_inv_value_in"
     */
    public function testPropertyLedgerInvValueIn()
    {
    }

    /**
     * Test attribute "ledger_movement_cog"
     */
    public function testPropertyLedgerMovementCog()
    {
    }

    /**
     * Test attribute "ledger_movement_cog_starts_with"
     */
    public function testPropertyLedgerMovementCogStartsWith()
    {
    }

    /**
     * Test attribute "ledger_movement_cog_ends_with"
     */
    public function testPropertyLedgerMovementCogEndsWith()
    {
    }

    /**
     * Test attribute "ledger_movement_cog_contains"
     */
    public function testPropertyLedgerMovementCogContains()
    {
    }

    /**
     * Test attribute "ledger_movement_cog_like"
     */
    public function testPropertyLedgerMovementCogLike()
    {
    }

    /**
     * Test attribute "ledger_movement_cog_between"
     */
    public function testPropertyLedgerMovementCogBetween()
    {
    }

    /**
     * Test attribute "ledger_movement_cog_in"
     */
    public function testPropertyLedgerMovementCogIn()
    {
    }

    /**
     * Test attribute "ledger_exp_asset"
     */
    public function testPropertyLedgerExpAsset()
    {
    }

    /**
     * Test attribute "ledger_exp_asset_starts_with"
     */
    public function testPropertyLedgerExpAssetStartsWith()
    {
    }

    /**
     * Test attribute "ledger_exp_asset_ends_with"
     */
    public function testPropertyLedgerExpAssetEndsWith()
    {
    }

    /**
     * Test attribute "ledger_exp_asset_contains"
     */
    public function testPropertyLedgerExpAssetContains()
    {
    }

    /**
     * Test attribute "ledger_exp_asset_like"
     */
    public function testPropertyLedgerExpAssetLike()
    {
    }

    /**
     * Test attribute "ledger_exp_asset_between"
     */
    public function testPropertyLedgerExpAssetBetween()
    {
    }

    /**
     * Test attribute "ledger_exp_asset_in"
     */
    public function testPropertyLedgerExpAssetIn()
    {
    }

    /**
     * Test attribute "ledger_exp_liab"
     */
    public function testPropertyLedgerExpLiab()
    {
    }

    /**
     * Test attribute "ledger_exp_liab_starts_with"
     */
    public function testPropertyLedgerExpLiabStartsWith()
    {
    }

    /**
     * Test attribute "ledger_exp_liab_ends_with"
     */
    public function testPropertyLedgerExpLiabEndsWith()
    {
    }

    /**
     * Test attribute "ledger_exp_liab_contains"
     */
    public function testPropertyLedgerExpLiabContains()
    {
    }

    /**
     * Test attribute "ledger_exp_liab_like"
     */
    public function testPropertyLedgerExpLiabLike()
    {
    }

    /**
     * Test attribute "ledger_exp_liab_between"
     */
    public function testPropertyLedgerExpLiabBetween()
    {
    }

    /**
     * Test attribute "ledger_exp_liab_in"
     */
    public function testPropertyLedgerExpLiabIn()
    {
    }

    /**
     * Test attribute "ledger_del_asset"
     */
    public function testPropertyLedgerDelAsset()
    {
    }

    /**
     * Test attribute "ledger_del_asset_starts_with"
     */
    public function testPropertyLedgerDelAssetStartsWith()
    {
    }

    /**
     * Test attribute "ledger_del_asset_ends_with"
     */
    public function testPropertyLedgerDelAssetEndsWith()
    {
    }

    /**
     * Test attribute "ledger_del_asset_contains"
     */
    public function testPropertyLedgerDelAssetContains()
    {
    }

    /**
     * Test attribute "ledger_del_asset_like"
     */
    public function testPropertyLedgerDelAssetLike()
    {
    }

    /**
     * Test attribute "ledger_del_asset_between"
     */
    public function testPropertyLedgerDelAssetBetween()
    {
    }

    /**
     * Test attribute "ledger_del_asset_in"
     */
    public function testPropertyLedgerDelAssetIn()
    {
    }

    /**
     * Test attribute "ledger_del_liab"
     */
    public function testPropertyLedgerDelLiab()
    {
    }

    /**
     * Test attribute "ledger_del_liab_starts_with"
     */
    public function testPropertyLedgerDelLiabStartsWith()
    {
    }

    /**
     * Test attribute "ledger_del_liab_ends_with"
     */
    public function testPropertyLedgerDelLiabEndsWith()
    {
    }

    /**
     * Test attribute "ledger_del_liab_contains"
     */
    public function testPropertyLedgerDelLiabContains()
    {
    }

    /**
     * Test attribute "ledger_del_liab_like"
     */
    public function testPropertyLedgerDelLiabLike()
    {
    }

    /**
     * Test attribute "ledger_del_liab_between"
     */
    public function testPropertyLedgerDelLiabBetween()
    {
    }

    /**
     * Test attribute "ledger_del_liab_in"
     */
    public function testPropertyLedgerDelLiabIn()
    {
    }

    /**
     * Test attribute "ledger_assigned_value"
     */
    public function testPropertyLedgerAssignedValue()
    {
    }

    /**
     * Test attribute "ledger_assigned_value_starts_with"
     */
    public function testPropertyLedgerAssignedValueStartsWith()
    {
    }

    /**
     * Test attribute "ledger_assigned_value_ends_with"
     */
    public function testPropertyLedgerAssignedValueEndsWith()
    {
    }

    /**
     * Test attribute "ledger_assigned_value_contains"
     */
    public function testPropertyLedgerAssignedValueContains()
    {
    }

    /**
     * Test attribute "ledger_assigned_value_like"
     */
    public function testPropertyLedgerAssignedValueLike()
    {
    }

    /**
     * Test attribute "ledger_assigned_value_between"
     */
    public function testPropertyLedgerAssignedValueBetween()
    {
    }

    /**
     * Test attribute "ledger_assigned_value_in"
     */
    public function testPropertyLedgerAssignedValueIn()
    {
    }

    /**
     * Test attribute "ledger_cog_variance"
     */
    public function testPropertyLedgerCogVariance()
    {
    }

    /**
     * Test attribute "ledger_cog_variance_starts_with"
     */
    public function testPropertyLedgerCogVarianceStartsWith()
    {
    }

    /**
     * Test attribute "ledger_cog_variance_ends_with"
     */
    public function testPropertyLedgerCogVarianceEndsWith()
    {
    }

    /**
     * Test attribute "ledger_cog_variance_contains"
     */
    public function testPropertyLedgerCogVarianceContains()
    {
    }

    /**
     * Test attribute "ledger_cog_variance_like"
     */
    public function testPropertyLedgerCogVarianceLike()
    {
    }

    /**
     * Test attribute "ledger_cog_variance_between"
     */
    public function testPropertyLedgerCogVarianceBetween()
    {
    }

    /**
     * Test attribute "ledger_cog_variance_in"
     */
    public function testPropertyLedgerCogVarianceIn()
    {
    }

    /**
     * Test attribute "ledger_inv_sales"
     */
    public function testPropertyLedgerInvSales()
    {
    }

    /**
     * Test attribute "ledger_inv_sales_starts_with"
     */
    public function testPropertyLedgerInvSalesStartsWith()
    {
    }

    /**
     * Test attribute "ledger_inv_sales_ends_with"
     */
    public function testPropertyLedgerInvSalesEndsWith()
    {
    }

    /**
     * Test attribute "ledger_inv_sales_contains"
     */
    public function testPropertyLedgerInvSalesContains()
    {
    }

    /**
     * Test attribute "ledger_inv_sales_like"
     */
    public function testPropertyLedgerInvSalesLike()
    {
    }

    /**
     * Test attribute "ledger_inv_sales_between"
     */
    public function testPropertyLedgerInvSalesBetween()
    {
    }

    /**
     * Test attribute "ledger_inv_sales_in"
     */
    public function testPropertyLedgerInvSalesIn()
    {
    }

    /**
     * Test attribute "ledger_accumulator"
     */
    public function testPropertyLedgerAccumulator()
    {
    }

    /**
     * Test attribute "ledger_accumulator_starts_with"
     */
    public function testPropertyLedgerAccumulatorStartsWith()
    {
    }

    /**
     * Test attribute "ledger_accumulator_ends_with"
     */
    public function testPropertyLedgerAccumulatorEndsWith()
    {
    }

    /**
     * Test attribute "ledger_accumulator_contains"
     */
    public function testPropertyLedgerAccumulatorContains()
    {
    }

    /**
     * Test attribute "ledger_accumulator_like"
     */
    public function testPropertyLedgerAccumulatorLike()
    {
    }

    /**
     * Test attribute "ledger_accumulator_between"
     */
    public function testPropertyLedgerAccumulatorBetween()
    {
    }

    /**
     * Test attribute "ledger_accumulator_in"
     */
    public function testPropertyLedgerAccumulatorIn()
    {
    }

    /**
     * Test attribute "ledger_purchases"
     */
    public function testPropertyLedgerPurchases()
    {
    }

    /**
     * Test attribute "ledger_purchases_starts_with"
     */
    public function testPropertyLedgerPurchasesStartsWith()
    {
    }

    /**
     * Test attribute "ledger_purchases_ends_with"
     */
    public function testPropertyLedgerPurchasesEndsWith()
    {
    }

    /**
     * Test attribute "ledger_purchases_contains"
     */
    public function testPropertyLedgerPurchasesContains()
    {
    }

    /**
     * Test attribute "ledger_purchases_like"
     */
    public function testPropertyLedgerPurchasesLike()
    {
    }

    /**
     * Test attribute "ledger_purchases_between"
     */
    public function testPropertyLedgerPurchasesBetween()
    {
    }

    /**
     * Test attribute "ledger_purchases_in"
     */
    public function testPropertyLedgerPurchasesIn()
    {
    }

    /**
     * Test attribute "ledger_ship_complete"
     */
    public function testPropertyLedgerShipComplete()
    {
    }

    /**
     * Test attribute "ledger_ship_complete_starts_with"
     */
    public function testPropertyLedgerShipCompleteStartsWith()
    {
    }

    /**
     * Test attribute "ledger_ship_complete_ends_with"
     */
    public function testPropertyLedgerShipCompleteEndsWith()
    {
    }

    /**
     * Test attribute "ledger_ship_complete_contains"
     */
    public function testPropertyLedgerShipCompleteContains()
    {
    }

    /**
     * Test attribute "ledger_ship_complete_like"
     */
    public function testPropertyLedgerShipCompleteLike()
    {
    }

    /**
     * Test attribute "ledger_ship_complete_between"
     */
    public function testPropertyLedgerShipCompleteBetween()
    {
    }

    /**
     * Test attribute "ledger_ship_complete_in"
     */
    public function testPropertyLedgerShipCompleteIn()
    {
    }

    /**
     * Test attribute "ledger_write_on"
     */
    public function testPropertyLedgerWriteOn()
    {
    }

    /**
     * Test attribute "ledger_write_on_starts_with"
     */
    public function testPropertyLedgerWriteOnStartsWith()
    {
    }

    /**
     * Test attribute "ledger_write_on_ends_with"
     */
    public function testPropertyLedgerWriteOnEndsWith()
    {
    }

    /**
     * Test attribute "ledger_write_on_contains"
     */
    public function testPropertyLedgerWriteOnContains()
    {
    }

    /**
     * Test attribute "ledger_write_on_like"
     */
    public function testPropertyLedgerWriteOnLike()
    {
    }

    /**
     * Test attribute "ledger_write_on_between"
     */
    public function testPropertyLedgerWriteOnBetween()
    {
    }

    /**
     * Test attribute "ledger_write_on_in"
     */
    public function testPropertyLedgerWriteOnIn()
    {
    }

    /**
     * Test attribute "ledger_write_off"
     */
    public function testPropertyLedgerWriteOff()
    {
    }

    /**
     * Test attribute "ledger_write_off_starts_with"
     */
    public function testPropertyLedgerWriteOffStartsWith()
    {
    }

    /**
     * Test attribute "ledger_write_off_ends_with"
     */
    public function testPropertyLedgerWriteOffEndsWith()
    {
    }

    /**
     * Test attribute "ledger_write_off_contains"
     */
    public function testPropertyLedgerWriteOffContains()
    {
    }

    /**
     * Test attribute "ledger_write_off_like"
     */
    public function testPropertyLedgerWriteOffLike()
    {
    }

    /**
     * Test attribute "ledger_write_off_between"
     */
    public function testPropertyLedgerWriteOffBetween()
    {
    }

    /**
     * Test attribute "ledger_write_off_in"
     */
    public function testPropertyLedgerWriteOffIn()
    {
    }

    /**
     * Test attribute "ledger_cost_price_adj"
     */
    public function testPropertyLedgerCostPriceAdj()
    {
    }

    /**
     * Test attribute "ledger_cost_price_adj_starts_with"
     */
    public function testPropertyLedgerCostPriceAdjStartsWith()
    {
    }

    /**
     * Test attribute "ledger_cost_price_adj_ends_with"
     */
    public function testPropertyLedgerCostPriceAdjEndsWith()
    {
    }

    /**
     * Test attribute "ledger_cost_price_adj_contains"
     */
    public function testPropertyLedgerCostPriceAdjContains()
    {
    }

    /**
     * Test attribute "ledger_cost_price_adj_like"
     */
    public function testPropertyLedgerCostPriceAdjLike()
    {
    }

    /**
     * Test attribute "ledger_cost_price_adj_between"
     */
    public function testPropertyLedgerCostPriceAdjBetween()
    {
    }

    /**
     * Test attribute "ledger_cost_price_adj_in"
     */
    public function testPropertyLedgerCostPriceAdjIn()
    {
    }

    /**
     * Test attribute "gst_inwards_id"
     */
    public function testPropertyGstInwardsId()
    {
    }

    /**
     * Test attribute "gst_inwards_id_starts_with"
     */
    public function testPropertyGstInwardsIdStartsWith()
    {
    }

    /**
     * Test attribute "gst_inwards_id_ends_with"
     */
    public function testPropertyGstInwardsIdEndsWith()
    {
    }

    /**
     * Test attribute "gst_inwards_id_contains"
     */
    public function testPropertyGstInwardsIdContains()
    {
    }

    /**
     * Test attribute "gst_inwards_id_like"
     */
    public function testPropertyGstInwardsIdLike()
    {
    }

    /**
     * Test attribute "gst_inwards_id_between"
     */
    public function testPropertyGstInwardsIdBetween()
    {
    }

    /**
     * Test attribute "gst_inwards_id_in"
     */
    public function testPropertyGstInwardsIdIn()
    {
    }

    /**
     * Test attribute "gst_outwards_id"
     */
    public function testPropertyGstOutwardsId()
    {
    }

    /**
     * Test attribute "gst_outwards_id_starts_with"
     */
    public function testPropertyGstOutwardsIdStartsWith()
    {
    }

    /**
     * Test attribute "gst_outwards_id_ends_with"
     */
    public function testPropertyGstOutwardsIdEndsWith()
    {
    }

    /**
     * Test attribute "gst_outwards_id_contains"
     */
    public function testPropertyGstOutwardsIdContains()
    {
    }

    /**
     * Test attribute "gst_outwards_id_like"
     */
    public function testPropertyGstOutwardsIdLike()
    {
    }

    /**
     * Test attribute "gst_outwards_id_between"
     */
    public function testPropertyGstOutwardsIdBetween()
    {
    }

    /**
     * Test attribute "gst_outwards_id_in"
     */
    public function testPropertyGstOutwardsIdIn()
    {
    }

    /**
     * Test attribute "gst_adjustments_inid"
     */
    public function testPropertyGstAdjustmentsInid()
    {
    }

    /**
     * Test attribute "gst_adjustments_inid_starts_with"
     */
    public function testPropertyGstAdjustmentsInidStartsWith()
    {
    }

    /**
     * Test attribute "gst_adjustments_inid_ends_with"
     */
    public function testPropertyGstAdjustmentsInidEndsWith()
    {
    }

    /**
     * Test attribute "gst_adjustments_inid_contains"
     */
    public function testPropertyGstAdjustmentsInidContains()
    {
    }

    /**
     * Test attribute "gst_adjustments_inid_like"
     */
    public function testPropertyGstAdjustmentsInidLike()
    {
    }

    /**
     * Test attribute "gst_adjustments_inid_between"
     */
    public function testPropertyGstAdjustmentsInidBetween()
    {
    }

    /**
     * Test attribute "gst_adjustments_inid_in"
     */
    public function testPropertyGstAdjustmentsInidIn()
    {
    }

    /**
     * Test attribute "gst_adjustments_outid"
     */
    public function testPropertyGstAdjustmentsOutid()
    {
    }

    /**
     * Test attribute "gst_adjustments_outid_starts_with"
     */
    public function testPropertyGstAdjustmentsOutidStartsWith()
    {
    }

    /**
     * Test attribute "gst_adjustments_outid_ends_with"
     */
    public function testPropertyGstAdjustmentsOutidEndsWith()
    {
    }

    /**
     * Test attribute "gst_adjustments_outid_contains"
     */
    public function testPropertyGstAdjustmentsOutidContains()
    {
    }

    /**
     * Test attribute "gst_adjustments_outid_like"
     */
    public function testPropertyGstAdjustmentsOutidLike()
    {
    }

    /**
     * Test attribute "gst_adjustments_outid_between"
     */
    public function testPropertyGstAdjustmentsOutidBetween()
    {
    }

    /**
     * Test attribute "gst_adjustments_outid_in"
     */
    public function testPropertyGstAdjustmentsOutidIn()
    {
    }

    /**
     * Test attribute "web_enabled"
     */
    public function testPropertyWebEnabled()
    {
    }

    /**
     * Test attribute "default_classification"
     */
    public function testPropertyDefaultClassification()
    {
    }

    /**
     * Test attribute "pricing_group_id"
     */
    public function testPropertyPricingGroupId()
    {
    }

    /**
     * Test attribute "pricing_group_id_starts_with"
     */
    public function testPropertyPricingGroupIdStartsWith()
    {
    }

    /**
     * Test attribute "pricing_group_id_ends_with"
     */
    public function testPropertyPricingGroupIdEndsWith()
    {
    }

    /**
     * Test attribute "pricing_group_id_contains"
     */
    public function testPropertyPricingGroupIdContains()
    {
    }

    /**
     * Test attribute "pricing_group_id_like"
     */
    public function testPropertyPricingGroupIdLike()
    {
    }

    /**
     * Test attribute "pricing_group_id_between"
     */
    public function testPropertyPricingGroupIdBetween()
    {
    }

    /**
     * Test attribute "pricing_group_id_in"
     */
    public function testPropertyPricingGroupIdIn()
    {
    }

    /**
     * Test attribute "skip"
     */
    public function testPropertySkip()
    {
    }

    /**
     * Test attribute "take"
     */
    public function testPropertyTake()
    {
    }

    /**
     * Test attribute "order_by"
     */
    public function testPropertyOrderBy()
    {
    }

    /**
     * Test attribute "order_by_desc"
     */
    public function testPropertyOrderByDesc()
    {
    }

    /**
     * Test attribute "include"
     */
    public function testPropertyInclude()
    {
    }

    /**
     * Test attribute "fields"
     */
    public function testPropertyFields()
    {
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
    }
}
