<?php
/**
 * INTransferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * INTransferTest Class Doc Comment
 *
 * @category    Class
 * @description IN_Transfer
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class INTransferTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "INTransfer"
     */
    public function testINTransfer()
    {
    }

    /**
     * Test attribute "transfer_id"
     */
    public function testPropertyTransferId()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "transfer_no"
     */
    public function testPropertyTransferNo()
    {
    }

    /**
     * Test attribute "transfer_date"
     */
    public function testPropertyTransferDate()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "in_logical_id"
     */
    public function testPropertyInLogicalId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "created_date_time"
     */
    public function testPropertyCreatedDateTime()
    {
    }

    /**
     * Test attribute "created_by_staff_id"
     */
    public function testPropertyCreatedByStaffId()
    {
    }

    /**
     * Test attribute "last_saved_by_staff_id"
     */
    public function testPropertyLastSavedByStaffId()
    {
    }

    /**
     * Test attribute "in_transfer_reasons_rec_id"
     */
    public function testPropertyInTransferReasonsRecId()
    {
    }
}
