<?php
/**
 * InventoryAttributeGroupTemplateAttributeGETRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * InventoryAttributeGroupTemplateAttributeGETRequestTest Class Doc Comment
 *
 * @category    Class
 * @description InventoryAttributeGroupTemplateAttributeGETRequest
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryAttributeGroupTemplateAttributeGETRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryAttributeGroupTemplateAttributeGETRequest"
     */
    public function testInventoryAttributeGroupTemplateAttributeGETRequest()
    {
    }

    /**
     * Test attribute "attribute_group_template_id"
     */
    public function testPropertyAttributeGroupTemplateId()
    {
    }

    /**
     * Test attribute "template_attribute_id"
     */
    public function testPropertyTemplateAttributeId()
    {
    }
}
