<?php
/**
 * InventoryBinLocationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * InventoryBinLocationTest Class Doc Comment
 *
 * @category    Class
 * @description InventoryBinLocation
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryBinLocationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryBinLocation"
     */
    public function testInventoryBinLocation()
    {
    }

    /**
     * Test attribute "bin_location_id"
     */
    public function testPropertyBinLocationId()
    {
    }

    /**
     * Test attribute "logical_warehouse_id"
     */
    public function testPropertyLogicalWarehouseId()
    {
    }

    /**
     * Test attribute "logical_warehouse_description"
     */
    public function testPropertyLogicalWarehouseDescription()
    {
    }

    /**
     * Test attribute "physical_warehouse_id"
     */
    public function testPropertyPhysicalWarehouseId()
    {
    }

    /**
     * Test attribute "physical_warehouse_description"
     */
    public function testPropertyPhysicalWarehouseDescription()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "item_no"
     */
    public function testPropertyItemNo()
    {
    }

    /**
     * Test attribute "is_default"
     */
    public function testPropertyIsDefault()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }
}
