<?php
/**
 * InventorySupplierWarehouseDELETERequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * InventorySupplierWarehouseDELETERequestTest Class Doc Comment
 *
 * @category    Class
 * @description InventorySupplierWarehouseDELETERequest
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventorySupplierWarehouseDELETERequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventorySupplierWarehouseDELETERequest"
     */
    public function testInventorySupplierWarehouseDELETERequest()
    {
    }

    /**
     * Test attribute "inventory_id"
     */
    public function testPropertyInventoryId()
    {
    }

    /**
     * Test attribute "region_name"
     */
    public function testPropertyRegionName()
    {
    }

    /**
     * Test attribute "supplier_id"
     */
    public function testPropertySupplierId()
    {
    }

    /**
     * Test attribute "supplier_warehouse_id"
     */
    public function testPropertySupplierWarehouseId()
    {
    }

    /**
     * Test attribute "default_warehouse"
     */
    public function testPropertyDefaultWarehouse()
    {
    }

    /**
     * Test attribute "home_suppliers_cost"
     */
    public function testPropertyHomeSuppliersCost()
    {
    }

    /**
     * Test attribute "suppliers_cost"
     */
    public function testPropertySuppliersCost()
    {
    }

    /**
     * Test attribute "suppliers_cost2"
     */
    public function testPropertySuppliersCost2()
    {
    }

    /**
     * Test attribute "home_suppliers_cost2"
     */
    public function testPropertyHomeSuppliersCost2()
    {
    }

    /**
     * Test attribute "supplier_soh"
     */
    public function testPropertySupplierSoh()
    {
    }

    /**
     * Test attribute "delivery_days"
     */
    public function testPropertyDeliveryDays()
    {
    }

    /**
     * Test attribute "spare_float1"
     */
    public function testPropertySpareFloat1()
    {
    }

    /**
     * Test attribute "spare_float2"
     */
    public function testPropertySpareFloat2()
    {
    }

    /**
     * Test attribute "spare_float3"
     */
    public function testPropertySpareFloat3()
    {
    }

    /**
     * Test attribute "spare_date1"
     */
    public function testPropertySpareDate1()
    {
    }

    /**
     * Test attribute "spare_date2"
     */
    public function testPropertySpareDate2()
    {
    }

    /**
     * Test attribute "spare_date3"
     */
    public function testPropertySpareDate3()
    {
    }

    /**
     * Test attribute "creditor_warehouse_id"
     */
    public function testPropertyCreditorWarehouseId()
    {
    }

    /**
     * Test attribute "creditor_warehouse_description"
     */
    public function testPropertyCreditorWarehouseDescription()
    {
    }

    /**
     * Test attribute "spare_string1"
     */
    public function testPropertySpareString1()
    {
    }

    /**
     * Test attribute "spare_string2"
     */
    public function testPropertySpareString2()
    {
    }

    /**
     * Test attribute "spare_string3"
     */
    public function testPropertySpareString3()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }

    /**
     * Test attribute "unit_of_measure"
     */
    public function testPropertyUnitOfMeasure()
    {
    }
}
