<?php
/**
 * InventorySupplierPOSTRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * InventorySupplierPOSTRequestTest Class Doc Comment
 *
 * @category    Class
 * @description InventorySupplierPOSTRequest
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventorySupplierPOSTRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventorySupplierPOSTRequest"
     */
    public function testInventorySupplierPOSTRequest()
    {
    }

    /**
     * Test attribute "inventory_id"
     */
    public function testPropertyInventoryId()
    {
    }

    /**
     * Test attribute "region_name"
     */
    public function testPropertyRegionName()
    {
    }

    /**
     * Test attribute "fx_rate"
     */
    public function testPropertyFxRate()
    {
    }

    /**
     * Test attribute "default_supplier"
     */
    public function testPropertyDefaultSupplier()
    {
    }

    /**
     * Test attribute "spare_float1"
     */
    public function testPropertySpareFloat1()
    {
    }

    /**
     * Test attribute "spare_float2"
     */
    public function testPropertySpareFloat2()
    {
    }

    /**
     * Test attribute "spare_float3"
     */
    public function testPropertySpareFloat3()
    {
    }

    /**
     * Test attribute "spare_date1"
     */
    public function testPropertySpareDate1()
    {
    }

    /**
     * Test attribute "spare_date2"
     */
    public function testPropertySpareDate2()
    {
    }

    /**
     * Test attribute "spare_date3"
     */
    public function testPropertySpareDate3()
    {
    }

    /**
     * Test attribute "creditor_id"
     */
    public function testPropertyCreditorId()
    {
    }

    /**
     * Test attribute "creditor_account_no"
     */
    public function testPropertyCreditorAccountNo()
    {
    }

    /**
     * Test attribute "creditor_name"
     */
    public function testPropertyCreditorName()
    {
    }

    /**
     * Test attribute "supplier_part_no"
     */
    public function testPropertySupplierPartNo()
    {
    }

    /**
     * Test attribute "supplier_upc"
     */
    public function testPropertySupplierUpc()
    {
    }

    /**
     * Test attribute "spare_string1"
     */
    public function testPropertySpareString1()
    {
    }

    /**
     * Test attribute "spare_string2"
     */
    public function testPropertySpareString2()
    {
    }

    /**
     * Test attribute "spare_string3"
     */
    public function testPropertySpareString3()
    {
    }

    /**
     * Test attribute "custom_field_values"
     */
    public function testPropertyCustomFieldValues()
    {
    }

    /**
     * Test attribute "supplier_warehouses"
     */
    public function testPropertySupplierWarehouses()
    {
    }

    /**
     * Test attribute "supplier_quantity_price_breaks"
     */
    public function testPropertySupplierQuantityPriceBreaks()
    {
    }
}
