<?php
/**
 * PIMainTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * PIMainTest Class Doc Comment
 *
 * @category    Class
 * @description PI_Main
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PIMainTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PIMain"
     */
    public function testPIMain()
    {
    }

    /**
     * Test attribute "pi_main_id"
     */
    public function testPropertyPiMainId()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "invoice_no"
     */
    public function testPropertyInvoiceNo()
    {
    }

    /**
     * Test attribute "creditor_id"
     */
    public function testPropertyCreditorId()
    {
    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "freight"
     */
    public function testPropertyFreight()
    {
    }

    /**
     * Test attribute "duty"
     */
    public function testPropertyDuty()
    {
    }

    /**
     * Test attribute "insurance"
     */
    public function testPropertyInsurance()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "in_logical_id"
     */
    public function testPropertyInLogicalId()
    {
    }

    /**
     * Test attribute "total_line_tax"
     */
    public function testPropertyTotalLineTax()
    {
    }

    /**
     * Test attribute "adj_tax"
     */
    public function testPropertyAdjTax()
    {
    }

    /**
     * Test attribute "freight_tax_id"
     */
    public function testPropertyFreightTaxId()
    {
    }

    /**
     * Test attribute "freight_tax_rate"
     */
    public function testPropertyFreightTaxRate()
    {
    }

    /**
     * Test attribute "freight_tax_amount"
     */
    public function testPropertyFreightTaxAmount()
    {
    }

    /**
     * Test attribute "duty_tax_id"
     */
    public function testPropertyDutyTaxId()
    {
    }

    /**
     * Test attribute "duty_tax_rate"
     */
    public function testPropertyDutyTaxRate()
    {
    }

    /**
     * Test attribute "duty_tax_amount"
     */
    public function testPropertyDutyTaxAmount()
    {
    }

    /**
     * Test attribute "insurance_tax_id"
     */
    public function testPropertyInsuranceTaxId()
    {
    }

    /**
     * Test attribute "insurance_tax_rate"
     */
    public function testPropertyInsuranceTaxRate()
    {
    }

    /**
     * Test attribute "insurance_tax_amount"
     */
    public function testPropertyInsuranceTaxAmount()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "decimal_places"
     */
    public function testPropertyDecimalPlaces()
    {
    }

    /**
     * Test attribute "fx_decimal_places"
     */
    public function testPropertyFxDecimalPlaces()
    {
    }
}
