<?php
/**
 * ShipmentImportCostTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * ShipmentImportCostTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentImportCost
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentImportCostTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShipmentImportCost"
     */
    public function testShipmentImportCost()
    {
    }

    /**
     * Test attribute "import_cost_id"
     */
    public function testPropertyImportCostId()
    {
    }

    /**
     * Test attribute "item_no"
     */
    public function testPropertyItemNo()
    {
    }

    /**
     * Test attribute "creditor_id"
     */
    public function testPropertyCreditorId()
    {
    }

    /**
     * Test attribute "creditor_account_no"
     */
    public function testPropertyCreditorAccountNo()
    {
    }

    /**
     * Test attribute "creditor_name"
     */
    public function testPropertyCreditorName()
    {
    }

    /**
     * Test attribute "cost_type"
     */
    public function testPropertyCostType()
    {
    }

    /**
     * Test attribute "use_forward_cover_contract"
     */
    public function testPropertyUseForwardCoverContract()
    {
    }

    /**
     * Test attribute "fx_rate"
     */
    public function testPropertyFxRate()
    {
    }

    /**
     * Test attribute "fx_amount"
     */
    public function testPropertyFxAmount()
    {
    }

    /**
     * Test attribute "home_amount"
     */
    public function testPropertyHomeAmount()
    {
    }

    /**
     * Test attribute "tax_rate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "tax_amount"
     */
    public function testPropertyTaxAmount()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "apportioned_on_purchase_orders"
     */
    public function testPropertyApportionedOnPurchaseOrders()
    {
    }

    /**
     * Test attribute "apportion_method"
     */
    public function testPropertyApportionMethod()
    {
    }

    /**
     * Test attribute "apportioned"
     */
    public function testPropertyApportioned()
    {
    }

    /**
     * Test attribute "invoiced"
     */
    public function testPropertyInvoiced()
    {
    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "invoice_no"
     */
    public function testPropertyInvoiceNo()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "cr_trans_id"
     */
    public function testPropertyCrTransId()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "user_field1"
     */
    public function testPropertyUserField1()
    {
    }

    /**
     * Test attribute "user_field2"
     */
    public function testPropertyUserField2()
    {
    }

    /**
     * Test attribute "user_field3"
     */
    public function testPropertyUserField3()
    {
    }

    /**
     * Test attribute "user_field4"
     */
    public function testPropertyUserField4()
    {
    }

    /**
     * Test attribute "user_field5"
     */
    public function testPropertyUserField5()
    {
    }

    /**
     * Test attribute "user_field6"
     */
    public function testPropertyUserField6()
    {
    }

    /**
     * Test attribute "user_field7"
     */
    public function testPropertyUserField7()
    {
    }

    /**
     * Test attribute "user_field8"
     */
    public function testPropertyUserField8()
    {
    }

    /**
     * Test attribute "user_field9"
     */
    public function testPropertyUserField9()
    {
    }

    /**
     * Test attribute "user_field10"
     */
    public function testPropertyUserField10()
    {
    }
}
