<?php
/**
 * VJiwaDebtorListQueryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * VJiwaDebtorListQueryTest Class Doc Comment
 *
 * @category    Class
 * @description v_Jiwa_Debtor_ListQuery
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VJiwaDebtorListQueryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VJiwaDebtorListQuery"
     */
    public function testVJiwaDebtorListQuery()
    {
    }

    /**
     * Test attribute "debtor_id"
     */
    public function testPropertyDebtorId()
    {
    }

    /**
     * Test attribute "debtor_id_starts_with"
     */
    public function testPropertyDebtorIdStartsWith()
    {
    }

    /**
     * Test attribute "debtor_id_ends_with"
     */
    public function testPropertyDebtorIdEndsWith()
    {
    }

    /**
     * Test attribute "debtor_id_contains"
     */
    public function testPropertyDebtorIdContains()
    {
    }

    /**
     * Test attribute "debtor_id_like"
     */
    public function testPropertyDebtorIdLike()
    {
    }

    /**
     * Test attribute "debtor_id_between"
     */
    public function testPropertyDebtorIdBetween()
    {
    }

    /**
     * Test attribute "debtor_id_in"
     */
    public function testPropertyDebtorIdIn()
    {
    }

    /**
     * Test attribute "account_no"
     */
    public function testPropertyAccountNo()
    {
    }

    /**
     * Test attribute "account_no_starts_with"
     */
    public function testPropertyAccountNoStartsWith()
    {
    }

    /**
     * Test attribute "account_no_ends_with"
     */
    public function testPropertyAccountNoEndsWith()
    {
    }

    /**
     * Test attribute "account_no_contains"
     */
    public function testPropertyAccountNoContains()
    {
    }

    /**
     * Test attribute "account_no_like"
     */
    public function testPropertyAccountNoLike()
    {
    }

    /**
     * Test attribute "account_no_between"
     */
    public function testPropertyAccountNoBetween()
    {
    }

    /**
     * Test attribute "account_no_in"
     */
    public function testPropertyAccountNoIn()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "name_starts_with"
     */
    public function testPropertyNameStartsWith()
    {
    }

    /**
     * Test attribute "name_ends_with"
     */
    public function testPropertyNameEndsWith()
    {
    }

    /**
     * Test attribute "name_contains"
     */
    public function testPropertyNameContains()
    {
    }

    /**
     * Test attribute "name_like"
     */
    public function testPropertyNameLike()
    {
    }

    /**
     * Test attribute "name_between"
     */
    public function testPropertyNameBetween()
    {
    }

    /**
     * Test attribute "name_in"
     */
    public function testPropertyNameIn()
    {
    }

    /**
     * Test attribute "alt_account_no"
     */
    public function testPropertyAltAccountNo()
    {
    }

    /**
     * Test attribute "alt_account_no_starts_with"
     */
    public function testPropertyAltAccountNoStartsWith()
    {
    }

    /**
     * Test attribute "alt_account_no_ends_with"
     */
    public function testPropertyAltAccountNoEndsWith()
    {
    }

    /**
     * Test attribute "alt_account_no_contains"
     */
    public function testPropertyAltAccountNoContains()
    {
    }

    /**
     * Test attribute "alt_account_no_like"
     */
    public function testPropertyAltAccountNoLike()
    {
    }

    /**
     * Test attribute "alt_account_no_between"
     */
    public function testPropertyAltAccountNoBetween()
    {
    }

    /**
     * Test attribute "alt_account_no_in"
     */
    public function testPropertyAltAccountNoIn()
    {
    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {
    }

    /**
     * Test attribute "address1_starts_with"
     */
    public function testPropertyAddress1StartsWith()
    {
    }

    /**
     * Test attribute "address1_ends_with"
     */
    public function testPropertyAddress1EndsWith()
    {
    }

    /**
     * Test attribute "address1_contains"
     */
    public function testPropertyAddress1Contains()
    {
    }

    /**
     * Test attribute "address1_like"
     */
    public function testPropertyAddress1Like()
    {
    }

    /**
     * Test attribute "address1_between"
     */
    public function testPropertyAddress1Between()
    {
    }

    /**
     * Test attribute "address1_in"
     */
    public function testPropertyAddress1In()
    {
    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "address2_starts_with"
     */
    public function testPropertyAddress2StartsWith()
    {
    }

    /**
     * Test attribute "address2_ends_with"
     */
    public function testPropertyAddress2EndsWith()
    {
    }

    /**
     * Test attribute "address2_contains"
     */
    public function testPropertyAddress2Contains()
    {
    }

    /**
     * Test attribute "address2_like"
     */
    public function testPropertyAddress2Like()
    {
    }

    /**
     * Test attribute "address2_between"
     */
    public function testPropertyAddress2Between()
    {
    }

    /**
     * Test attribute "address2_in"
     */
    public function testPropertyAddress2In()
    {
    }

    /**
     * Test attribute "address3"
     */
    public function testPropertyAddress3()
    {
    }

    /**
     * Test attribute "address3_starts_with"
     */
    public function testPropertyAddress3StartsWith()
    {
    }

    /**
     * Test attribute "address3_ends_with"
     */
    public function testPropertyAddress3EndsWith()
    {
    }

    /**
     * Test attribute "address3_contains"
     */
    public function testPropertyAddress3Contains()
    {
    }

    /**
     * Test attribute "address3_like"
     */
    public function testPropertyAddress3Like()
    {
    }

    /**
     * Test attribute "address3_between"
     */
    public function testPropertyAddress3Between()
    {
    }

    /**
     * Test attribute "address3_in"
     */
    public function testPropertyAddress3In()
    {
    }

    /**
     * Test attribute "address4"
     */
    public function testPropertyAddress4()
    {
    }

    /**
     * Test attribute "address4_starts_with"
     */
    public function testPropertyAddress4StartsWith()
    {
    }

    /**
     * Test attribute "address4_ends_with"
     */
    public function testPropertyAddress4EndsWith()
    {
    }

    /**
     * Test attribute "address4_contains"
     */
    public function testPropertyAddress4Contains()
    {
    }

    /**
     * Test attribute "address4_like"
     */
    public function testPropertyAddress4Like()
    {
    }

    /**
     * Test attribute "address4_between"
     */
    public function testPropertyAddress4Between()
    {
    }

    /**
     * Test attribute "address4_in"
     */
    public function testPropertyAddress4In()
    {
    }

    /**
     * Test attribute "post_code"
     */
    public function testPropertyPostCode()
    {
    }

    /**
     * Test attribute "post_code_starts_with"
     */
    public function testPropertyPostCodeStartsWith()
    {
    }

    /**
     * Test attribute "post_code_ends_with"
     */
    public function testPropertyPostCodeEndsWith()
    {
    }

    /**
     * Test attribute "post_code_contains"
     */
    public function testPropertyPostCodeContains()
    {
    }

    /**
     * Test attribute "post_code_like"
     */
    public function testPropertyPostCodeLike()
    {
    }

    /**
     * Test attribute "post_code_between"
     */
    public function testPropertyPostCodeBetween()
    {
    }

    /**
     * Test attribute "post_code_in"
     */
    public function testPropertyPostCodeIn()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "country_starts_with"
     */
    public function testPropertyCountryStartsWith()
    {
    }

    /**
     * Test attribute "country_ends_with"
     */
    public function testPropertyCountryEndsWith()
    {
    }

    /**
     * Test attribute "country_contains"
     */
    public function testPropertyCountryContains()
    {
    }

    /**
     * Test attribute "country_like"
     */
    public function testPropertyCountryLike()
    {
    }

    /**
     * Test attribute "country_between"
     */
    public function testPropertyCountryBetween()
    {
    }

    /**
     * Test attribute "country_in"
     */
    public function testPropertyCountryIn()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "phone_starts_with"
     */
    public function testPropertyPhoneStartsWith()
    {
    }

    /**
     * Test attribute "phone_ends_with"
     */
    public function testPropertyPhoneEndsWith()
    {
    }

    /**
     * Test attribute "phone_contains"
     */
    public function testPropertyPhoneContains()
    {
    }

    /**
     * Test attribute "phone_like"
     */
    public function testPropertyPhoneLike()
    {
    }

    /**
     * Test attribute "phone_between"
     */
    public function testPropertyPhoneBetween()
    {
    }

    /**
     * Test attribute "phone_in"
     */
    public function testPropertyPhoneIn()
    {
    }

    /**
     * Test attribute "account_on_hold"
     */
    public function testPropertyAccountOnHold()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "email_address_starts_with"
     */
    public function testPropertyEmailAddressStartsWith()
    {
    }

    /**
     * Test attribute "email_address_ends_with"
     */
    public function testPropertyEmailAddressEndsWith()
    {
    }

    /**
     * Test attribute "email_address_contains"
     */
    public function testPropertyEmailAddressContains()
    {
    }

    /**
     * Test attribute "email_address_like"
     */
    public function testPropertyEmailAddressLike()
    {
    }

    /**
     * Test attribute "email_address_between"
     */
    public function testPropertyEmailAddressBetween()
    {
    }

    /**
     * Test attribute "email_address_in"
     */
    public function testPropertyEmailAddressIn()
    {
    }

    /**
     * Test attribute "current_balance"
     */
    public function testPropertyCurrentBalance()
    {
    }

    /**
     * Test attribute "current_balance_greater_than_or_equal_to"
     */
    public function testPropertyCurrentBalanceGreaterThanOrEqualTo()
    {
    }

    /**
     * Test attribute "current_balance_greater_than"
     */
    public function testPropertyCurrentBalanceGreaterThan()
    {
    }

    /**
     * Test attribute "current_balance_less_than"
     */
    public function testPropertyCurrentBalanceLessThan()
    {
    }

    /**
     * Test attribute "current_balance_less_than_or_equal_to"
     */
    public function testPropertyCurrentBalanceLessThanOrEqualTo()
    {
    }

    /**
     * Test attribute "current_balance_not_equal_to"
     */
    public function testPropertyCurrentBalanceNotEqualTo()
    {
    }

    /**
     * Test attribute "current_balance_between"
     */
    public function testPropertyCurrentBalanceBetween()
    {
    }

    /**
     * Test attribute "current_balance_in"
     */
    public function testPropertyCurrentBalanceIn()
    {
    }

    /**
     * Test attribute "web_access"
     */
    public function testPropertyWebAccess()
    {
    }

    /**
     * Test attribute "last_saved_date_time"
     */
    public function testPropertyLastSavedDateTime()
    {
    }

    /**
     * Test attribute "last_saved_date_time_greater_than_or_equal_to"
     */
    public function testPropertyLastSavedDateTimeGreaterThanOrEqualTo()
    {
    }

    /**
     * Test attribute "last_saved_date_time_greater_than"
     */
    public function testPropertyLastSavedDateTimeGreaterThan()
    {
    }

    /**
     * Test attribute "last_saved_date_time_less_than"
     */
    public function testPropertyLastSavedDateTimeLessThan()
    {
    }

    /**
     * Test attribute "last_saved_date_time_less_than_or_equal_to"
     */
    public function testPropertyLastSavedDateTimeLessThanOrEqualTo()
    {
    }

    /**
     * Test attribute "last_saved_date_time_not_equal_to"
     */
    public function testPropertyLastSavedDateTimeNotEqualTo()
    {
    }

    /**
     * Test attribute "last_saved_date_time_between"
     */
    public function testPropertyLastSavedDateTimeBetween()
    {
    }

    /**
     * Test attribute "last_saved_date_time_in"
     */
    public function testPropertyLastSavedDateTimeIn()
    {
    }

    /**
     * Test attribute "trading_status"
     */
    public function testPropertyTradingStatus()
    {
    }

    /**
     * Test attribute "trading_status_greater_than_or_equal_to"
     */
    public function testPropertyTradingStatusGreaterThanOrEqualTo()
    {
    }

    /**
     * Test attribute "trading_status_greater_than"
     */
    public function testPropertyTradingStatusGreaterThan()
    {
    }

    /**
     * Test attribute "trading_status_less_than"
     */
    public function testPropertyTradingStatusLessThan()
    {
    }

    /**
     * Test attribute "trading_status_less_than_or_equal_to"
     */
    public function testPropertyTradingStatusLessThanOrEqualTo()
    {
    }

    /**
     * Test attribute "trading_status_not_equal_to"
     */
    public function testPropertyTradingStatusNotEqualTo()
    {
    }

    /**
     * Test attribute "trading_status_between"
     */
    public function testPropertyTradingStatusBetween()
    {
    }

    /**
     * Test attribute "trading_status_in"
     */
    public function testPropertyTradingStatusIn()
    {
    }

    /**
     * Test attribute "debtor_classification_id"
     */
    public function testPropertyDebtorClassificationId()
    {
    }

    /**
     * Test attribute "debtor_classification_id_starts_with"
     */
    public function testPropertyDebtorClassificationIdStartsWith()
    {
    }

    /**
     * Test attribute "debtor_classification_id_ends_with"
     */
    public function testPropertyDebtorClassificationIdEndsWith()
    {
    }

    /**
     * Test attribute "debtor_classification_id_contains"
     */
    public function testPropertyDebtorClassificationIdContains()
    {
    }

    /**
     * Test attribute "debtor_classification_id_like"
     */
    public function testPropertyDebtorClassificationIdLike()
    {
    }

    /**
     * Test attribute "debtor_classification_id_between"
     */
    public function testPropertyDebtorClassificationIdBetween()
    {
    }

    /**
     * Test attribute "debtor_classification_id_in"
     */
    public function testPropertyDebtorClassificationIdIn()
    {
    }

    /**
     * Test attribute "classification_description"
     */
    public function testPropertyClassificationDescription()
    {
    }

    /**
     * Test attribute "classification_description_starts_with"
     */
    public function testPropertyClassificationDescriptionStartsWith()
    {
    }

    /**
     * Test attribute "classification_description_ends_with"
     */
    public function testPropertyClassificationDescriptionEndsWith()
    {
    }

    /**
     * Test attribute "classification_description_contains"
     */
    public function testPropertyClassificationDescriptionContains()
    {
    }

    /**
     * Test attribute "classification_description_like"
     */
    public function testPropertyClassificationDescriptionLike()
    {
    }

    /**
     * Test attribute "classification_description_between"
     */
    public function testPropertyClassificationDescriptionBetween()
    {
    }

    /**
     * Test attribute "classification_description_in"
     */
    public function testPropertyClassificationDescriptionIn()
    {
    }

    /**
     * Test attribute "category1_id"
     */
    public function testPropertyCategory1Id()
    {
    }

    /**
     * Test attribute "category1_id_starts_with"
     */
    public function testPropertyCategory1IdStartsWith()
    {
    }

    /**
     * Test attribute "category1_id_ends_with"
     */
    public function testPropertyCategory1IdEndsWith()
    {
    }

    /**
     * Test attribute "category1_id_contains"
     */
    public function testPropertyCategory1IdContains()
    {
    }

    /**
     * Test attribute "category1_id_like"
     */
    public function testPropertyCategory1IdLike()
    {
    }

    /**
     * Test attribute "category1_id_between"
     */
    public function testPropertyCategory1IdBetween()
    {
    }

    /**
     * Test attribute "category1_id_in"
     */
    public function testPropertyCategory1IdIn()
    {
    }

    /**
     * Test attribute "category1_description"
     */
    public function testPropertyCategory1Description()
    {
    }

    /**
     * Test attribute "category1_description_starts_with"
     */
    public function testPropertyCategory1DescriptionStartsWith()
    {
    }

    /**
     * Test attribute "category1_description_ends_with"
     */
    public function testPropertyCategory1DescriptionEndsWith()
    {
    }

    /**
     * Test attribute "category1_description_contains"
     */
    public function testPropertyCategory1DescriptionContains()
    {
    }

    /**
     * Test attribute "category1_description_like"
     */
    public function testPropertyCategory1DescriptionLike()
    {
    }

    /**
     * Test attribute "category1_description_between"
     */
    public function testPropertyCategory1DescriptionBetween()
    {
    }

    /**
     * Test attribute "category1_description_in"
     */
    public function testPropertyCategory1DescriptionIn()
    {
    }

    /**
     * Test attribute "category2_id"
     */
    public function testPropertyCategory2Id()
    {
    }

    /**
     * Test attribute "category2_id_starts_with"
     */
    public function testPropertyCategory2IdStartsWith()
    {
    }

    /**
     * Test attribute "category2_id_ends_with"
     */
    public function testPropertyCategory2IdEndsWith()
    {
    }

    /**
     * Test attribute "category2_id_contains"
     */
    public function testPropertyCategory2IdContains()
    {
    }

    /**
     * Test attribute "category2_id_like"
     */
    public function testPropertyCategory2IdLike()
    {
    }

    /**
     * Test attribute "category2_id_between"
     */
    public function testPropertyCategory2IdBetween()
    {
    }

    /**
     * Test attribute "category2_id_in"
     */
    public function testPropertyCategory2IdIn()
    {
    }

    /**
     * Test attribute "category2_description"
     */
    public function testPropertyCategory2Description()
    {
    }

    /**
     * Test attribute "category2_description_starts_with"
     */
    public function testPropertyCategory2DescriptionStartsWith()
    {
    }

    /**
     * Test attribute "category2_description_ends_with"
     */
    public function testPropertyCategory2DescriptionEndsWith()
    {
    }

    /**
     * Test attribute "category2_description_contains"
     */
    public function testPropertyCategory2DescriptionContains()
    {
    }

    /**
     * Test attribute "category2_description_like"
     */
    public function testPropertyCategory2DescriptionLike()
    {
    }

    /**
     * Test attribute "category2_description_between"
     */
    public function testPropertyCategory2DescriptionBetween()
    {
    }

    /**
     * Test attribute "category2_description_in"
     */
    public function testPropertyCategory2DescriptionIn()
    {
    }

    /**
     * Test attribute "category3_id"
     */
    public function testPropertyCategory3Id()
    {
    }

    /**
     * Test attribute "category3_id_starts_with"
     */
    public function testPropertyCategory3IdStartsWith()
    {
    }

    /**
     * Test attribute "category3_id_ends_with"
     */
    public function testPropertyCategory3IdEndsWith()
    {
    }

    /**
     * Test attribute "category3_id_contains"
     */
    public function testPropertyCategory3IdContains()
    {
    }

    /**
     * Test attribute "category3_id_like"
     */
    public function testPropertyCategory3IdLike()
    {
    }

    /**
     * Test attribute "category3_id_between"
     */
    public function testPropertyCategory3IdBetween()
    {
    }

    /**
     * Test attribute "category3_id_in"
     */
    public function testPropertyCategory3IdIn()
    {
    }

    /**
     * Test attribute "category3_description"
     */
    public function testPropertyCategory3Description()
    {
    }

    /**
     * Test attribute "category3_description_starts_with"
     */
    public function testPropertyCategory3DescriptionStartsWith()
    {
    }

    /**
     * Test attribute "category3_description_ends_with"
     */
    public function testPropertyCategory3DescriptionEndsWith()
    {
    }

    /**
     * Test attribute "category3_description_contains"
     */
    public function testPropertyCategory3DescriptionContains()
    {
    }

    /**
     * Test attribute "category3_description_like"
     */
    public function testPropertyCategory3DescriptionLike()
    {
    }

    /**
     * Test attribute "category3_description_between"
     */
    public function testPropertyCategory3DescriptionBetween()
    {
    }

    /**
     * Test attribute "category3_description_in"
     */
    public function testPropertyCategory3DescriptionIn()
    {
    }

    /**
     * Test attribute "category4_id"
     */
    public function testPropertyCategory4Id()
    {
    }

    /**
     * Test attribute "category4_id_starts_with"
     */
    public function testPropertyCategory4IdStartsWith()
    {
    }

    /**
     * Test attribute "category4_id_ends_with"
     */
    public function testPropertyCategory4IdEndsWith()
    {
    }

    /**
     * Test attribute "category4_id_contains"
     */
    public function testPropertyCategory4IdContains()
    {
    }

    /**
     * Test attribute "category4_id_like"
     */
    public function testPropertyCategory4IdLike()
    {
    }

    /**
     * Test attribute "category4_id_between"
     */
    public function testPropertyCategory4IdBetween()
    {
    }

    /**
     * Test attribute "category4_id_in"
     */
    public function testPropertyCategory4IdIn()
    {
    }

    /**
     * Test attribute "category4_description"
     */
    public function testPropertyCategory4Description()
    {
    }

    /**
     * Test attribute "category4_description_starts_with"
     */
    public function testPropertyCategory4DescriptionStartsWith()
    {
    }

    /**
     * Test attribute "category4_description_ends_with"
     */
    public function testPropertyCategory4DescriptionEndsWith()
    {
    }

    /**
     * Test attribute "category4_description_contains"
     */
    public function testPropertyCategory4DescriptionContains()
    {
    }

    /**
     * Test attribute "category4_description_like"
     */
    public function testPropertyCategory4DescriptionLike()
    {
    }

    /**
     * Test attribute "category4_description_between"
     */
    public function testPropertyCategory4DescriptionBetween()
    {
    }

    /**
     * Test attribute "category4_description_in"
     */
    public function testPropertyCategory4DescriptionIn()
    {
    }

    /**
     * Test attribute "category5_id"
     */
    public function testPropertyCategory5Id()
    {
    }

    /**
     * Test attribute "category5_id_starts_with"
     */
    public function testPropertyCategory5IdStartsWith()
    {
    }

    /**
     * Test attribute "category5_id_ends_with"
     */
    public function testPropertyCategory5IdEndsWith()
    {
    }

    /**
     * Test attribute "category5_id_contains"
     */
    public function testPropertyCategory5IdContains()
    {
    }

    /**
     * Test attribute "category5_id_like"
     */
    public function testPropertyCategory5IdLike()
    {
    }

    /**
     * Test attribute "category5_id_between"
     */
    public function testPropertyCategory5IdBetween()
    {
    }

    /**
     * Test attribute "category5_id_in"
     */
    public function testPropertyCategory5IdIn()
    {
    }

    /**
     * Test attribute "category5_description"
     */
    public function testPropertyCategory5Description()
    {
    }

    /**
     * Test attribute "category5_description_starts_with"
     */
    public function testPropertyCategory5DescriptionStartsWith()
    {
    }

    /**
     * Test attribute "category5_description_ends_with"
     */
    public function testPropertyCategory5DescriptionEndsWith()
    {
    }

    /**
     * Test attribute "category5_description_contains"
     */
    public function testPropertyCategory5DescriptionContains()
    {
    }

    /**
     * Test attribute "category5_description_like"
     */
    public function testPropertyCategory5DescriptionLike()
    {
    }

    /**
     * Test attribute "category5_description_between"
     */
    public function testPropertyCategory5DescriptionBetween()
    {
    }

    /**
     * Test attribute "category5_description_in"
     */
    public function testPropertyCategory5DescriptionIn()
    {
    }

    /**
     * Test attribute "price_scheme_id"
     */
    public function testPropertyPriceSchemeId()
    {
    }

    /**
     * Test attribute "price_scheme_id_starts_with"
     */
    public function testPropertyPriceSchemeIdStartsWith()
    {
    }

    /**
     * Test attribute "price_scheme_id_ends_with"
     */
    public function testPropertyPriceSchemeIdEndsWith()
    {
    }

    /**
     * Test attribute "price_scheme_id_contains"
     */
    public function testPropertyPriceSchemeIdContains()
    {
    }

    /**
     * Test attribute "price_scheme_id_like"
     */
    public function testPropertyPriceSchemeIdLike()
    {
    }

    /**
     * Test attribute "price_scheme_id_between"
     */
    public function testPropertyPriceSchemeIdBetween()
    {
    }

    /**
     * Test attribute "price_scheme_id_in"
     */
    public function testPropertyPriceSchemeIdIn()
    {
    }

    /**
     * Test attribute "price_scheme_description"
     */
    public function testPropertyPriceSchemeDescription()
    {
    }

    /**
     * Test attribute "price_scheme_description_starts_with"
     */
    public function testPropertyPriceSchemeDescriptionStartsWith()
    {
    }

    /**
     * Test attribute "price_scheme_description_ends_with"
     */
    public function testPropertyPriceSchemeDescriptionEndsWith()
    {
    }

    /**
     * Test attribute "price_scheme_description_contains"
     */
    public function testPropertyPriceSchemeDescriptionContains()
    {
    }

    /**
     * Test attribute "price_scheme_description_like"
     */
    public function testPropertyPriceSchemeDescriptionLike()
    {
    }

    /**
     * Test attribute "price_scheme_description_between"
     */
    public function testPropertyPriceSchemeDescriptionBetween()
    {
    }

    /**
     * Test attribute "price_scheme_description_in"
     */
    public function testPropertyPriceSchemeDescriptionIn()
    {
    }

    /**
     * Test attribute "pricing_group_description"
     */
    public function testPropertyPricingGroupDescription()
    {
    }

    /**
     * Test attribute "pricing_group_description_starts_with"
     */
    public function testPropertyPricingGroupDescriptionStartsWith()
    {
    }

    /**
     * Test attribute "pricing_group_description_ends_with"
     */
    public function testPropertyPricingGroupDescriptionEndsWith()
    {
    }

    /**
     * Test attribute "pricing_group_description_contains"
     */
    public function testPropertyPricingGroupDescriptionContains()
    {
    }

    /**
     * Test attribute "pricing_group_description_like"
     */
    public function testPropertyPricingGroupDescriptionLike()
    {
    }

    /**
     * Test attribute "pricing_group_description_between"
     */
    public function testPropertyPricingGroupDescriptionBetween()
    {
    }

    /**
     * Test attribute "pricing_group_description_in"
     */
    public function testPropertyPricingGroupDescriptionIn()
    {
    }

    /**
     * Test attribute "skip"
     */
    public function testPropertySkip()
    {
    }

    /**
     * Test attribute "take"
     */
    public function testPropertyTake()
    {
    }

    /**
     * Test attribute "order_by"
     */
    public function testPropertyOrderBy()
    {
    }

    /**
     * Test attribute "order_by_desc"
     */
    public function testPropertyOrderByDesc()
    {
    }

    /**
     * Test attribute "include"
     */
    public function testPropertyInclude()
    {
    }

    /**
     * Test attribute "fields"
     */
    public function testPropertyFields()
    {
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
    }
}
