<?php
/**
 * WarehouseTransferInLineDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Jiwa;

/**
 * WarehouseTransferInLineDetailTest Class Doc Comment
 *
 * @category    Class
 * @description WarehouseTransferInLineDetail
 * @package     Jiwa
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WarehouseTransferInLineDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WarehouseTransferInLineDetail"
     */
    public function testWarehouseTransferInLineDetail()
    {
    }

    /**
     * Test attribute "transfer_line_details_id"
     */
    public function testPropertyTransferLineDetailsId()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
    }

    /**
     * Test attribute "source_serial_no"
     */
    public function testPropertySourceSerialNo()
    {
    }

    /**
     * Test attribute "source_bin_location"
     */
    public function testPropertySourceBinLocation()
    {
    }

    /**
     * Test attribute "source_expiry_date"
     */
    public function testPropertySourceExpiryDate()
    {
    }

    /**
     * Test attribute "source_date_in"
     */
    public function testPropertySourceDateIn()
    {
    }

    /**
     * Test attribute "source_special_price"
     */
    public function testPropertySourceSpecialPrice()
    {
    }

    /**
     * Test attribute "source_in_sohid"
     */
    public function testPropertySourceInSohid()
    {
    }

    /**
     * Test attribute "in_transit_in_sohid"
     */
    public function testPropertyInTransitInSohid()
    {
    }

    /**
     * Test attribute "destination_in_sohid"
     */
    public function testPropertyDestinationInSohid()
    {
    }

    /**
     * Test attribute "quantity_received"
     */
    public function testPropertyQuantityReceived()
    {
    }

    /**
     * Test attribute "cost_received"
     */
    public function testPropertyCostReceived()
    {
    }

    /**
     * Test attribute "destination_serial_no"
     */
    public function testPropertyDestinationSerialNo()
    {
    }

    /**
     * Test attribute "destination_bin_location"
     */
    public function testPropertyDestinationBinLocation()
    {
    }

    /**
     * Test attribute "destination_expiry_date"
     */
    public function testPropertyDestinationExpiryDate()
    {
    }

    /**
     * Test attribute "added_cost"
     */
    public function testPropertyAddedCost()
    {
    }
}
