<?php
/**
 * CurrenciesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Jiwa;

use \Jiwa\Configuration;
use \Jiwa\ApiException;
use \Jiwa\ObjectSerializer;

/**
 * CurrenciesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CurrenciesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for currencyABANDONRequestAbandonDelete
     *
     * Abandons a stateful currency..
     *
     */
    public function testCurrencyABANDONRequestAbandonDelete()
    {
    }

    /**
     * Test case for currencyDELETERequestCurrencyIDDelete
     *
     * Deletes a currency..
     *
     */
    public function testCurrencyDELETERequestCurrencyIDDelete()
    {
    }

    /**
     * Test case for currencyGETRequestCurrencyIDGet
     *
     * Retrieves a currency..
     *
     */
    public function testCurrencyGETRequestCurrencyIDGet()
    {
    }

    /**
     * Test case for currencyPATCHRequestCurrencyIDUpdate
     *
     * Updates a currency..
     *
     */
    public function testCurrencyPATCHRequestCurrencyIDUpdate()
    {
    }

    /**
     * Test case for currencyPOSTRequestPost
     *
     * Creates a currency..
     *
     */
    public function testCurrencyPOSTRequestPost()
    {
    }

    /**
     * Test case for currencyRateDELETERequestCurrencyIDRatesRateIDDelete
     *
     * Deletes a rate from a currency..
     *
     */
    public function testCurrencyRateDELETERequestCurrencyIDRatesRateIDDelete()
    {
    }

    /**
     * Test case for currencyRateGETRequestCurrencyIDRatesRateIDGet
     *
     * Retrieves a currency rate..
     *
     */
    public function testCurrencyRateGETRequestCurrencyIDRatesRateIDGet()
    {
    }

    /**
     * Test case for currencyRatePATCHRequestCurrencyIDRatesRateIDUpdate
     *
     * Updates a rate for a currency..
     *
     */
    public function testCurrencyRatePATCHRequestCurrencyIDRatesRateIDUpdate()
    {
    }

    /**
     * Test case for currencyRatePOSTRequestCurrencyIDRatesPost
     *
     * Appends a rate to a currency..
     *
     */
    public function testCurrencyRatePOSTRequestCurrencyIDRatesPost()
    {
    }

    /**
     * Test case for currencySAVERequestSaveGet
     *
     * Saves a stateful currency..
     *
     */
    public function testCurrencySAVERequestSaveGet()
    {
    }
}
