<?php
/**
 * GoodsReceivedNotesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JiwaAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Jiwa;

use \Jiwa\Configuration;
use \Jiwa\ApiException;
use \Jiwa\ObjectSerializer;

/**
 * GoodsReceivedNotesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Jiwa
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GoodsReceivedNotesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for goodsReceivedNoteABANDONRequestAbandonDelete
     *
     * Abandons a stateful goods received note..
     *
     */
    public function testGoodsReceivedNoteABANDONRequestAbandonDelete()
    {
    }

    /**
     * Test case for goodsReceivedNoteACTIVATERequestActivateGRNIDPost
     *
     * Activates a GRN..
     *
     */
    public function testGoodsReceivedNoteACTIVATERequestActivateGRNIDPost()
    {
    }

    /**
     * Test case for goodsReceivedNoteCREATEFromPOLinesRequestFromPurchaseOrderLinesPost
     *
     * Creates a GRN from the supplied list of ReceivedPOLineQuantity..
     *
     */
    public function testGoodsReceivedNoteCREATEFromPOLinesRequestFromPurchaseOrderLinesPost()
    {
    }

    /**
     * Test case for goodsReceivedNoteCREATEFromPORequestFromPurchaseOrdersOrderNosPost
     *
     * Creates a GRN from the supplied purchase orders..
     *
     */
    public function testGoodsReceivedNoteCREATEFromPORequestFromPurchaseOrdersOrderNosPost()
    {
    }

    /**
     * Test case for goodsReceivedNoteDELETERequestGRNIDDelete
     *
     * Deletes a GRN..
     *
     */
    public function testGoodsReceivedNoteDELETERequestGRNIDDelete()
    {
    }

    /**
     * Test case for goodsReceivedNoteGETRequestGRNIDGet
     *
     * Retrieves a GRN..
     *
     */
    public function testGoodsReceivedNoteGETRequestGRNIDGet()
    {
    }

    /**
     * Test case for goodsReceivedNoteLineDELETERequestGRNIDLinesLineIDDelete
     *
     * Deletes a line from a goods received note..
     *
     */
    public function testGoodsReceivedNoteLineDELETERequestGRNIDLinesLineIDDelete()
    {
    }

    /**
     * Test case for goodsReceivedNoteLineDetailDELETERequestGRNIDLinesLineIDLineDetailsLineDetailIDDelete
     *
     * Deletes a goods received note line detail..
     *
     */
    public function testGoodsReceivedNoteLineDetailDELETERequestGRNIDLinesLineIDLineDetailsLineDetailIDDelete()
    {
    }

    /**
     * Test case for goodsReceivedNoteLineDetailGETRequestGRNIDLinesLineIDLineDetailsLineDetailIDGet
     *
     * Retrieves a goods received note line detail..
     *
     */
    public function testGoodsReceivedNoteLineDetailGETRequestGRNIDLinesLineIDLineDetailsLineDetailIDGet()
    {
    }

    /**
     * Test case for goodsReceivedNoteLineDetailPATCHRequestGRNIDLinesLineIDLineDetailsLineDetailIDUpdate
     *
     * Updates a goods received note line detail..
     *
     */
    public function testGoodsReceivedNoteLineDetailPATCHRequestGRNIDLinesLineIDLineDetailsLineDetailIDUpdate()
    {
    }

    /**
     * Test case for goodsReceivedNoteLineDetailPOSTRequestGRNIDLinesLineIDLineDetailsPost
     *
     * Appends a line detail to a goods received note line..
     *
     */
    public function testGoodsReceivedNoteLineDetailPOSTRequestGRNIDLinesLineIDLineDetailsPost()
    {
    }

    /**
     * Test case for goodsReceivedNoteLineDetailPUTRequestGRNIDLinesLineIDLineDetailsCreate
     *
     * Sets the line details for a goods received note line. Existing line details for that line will be replaced..
     *
     */
    public function testGoodsReceivedNoteLineDetailPUTRequestGRNIDLinesLineIDLineDetailsCreate()
    {
    }

    /**
     * Test case for goodsReceivedNoteLineDetailsGETManyRequestGRNIDLinesLineIDLineDetailsGet
     *
     * Retrieves a list of line details for a goods received note line..
     *
     */
    public function testGoodsReceivedNoteLineDetailsGETManyRequestGRNIDLinesLineIDLineDetailsGet()
    {
    }

    /**
     * Test case for goodsReceivedNoteLineGETRequestGRNIDLinesLineIDGet
     *
     * Retrieves a goods received note line..
     *
     */
    public function testGoodsReceivedNoteLineGETRequestGRNIDLinesLineIDGet()
    {
    }

    /**
     * Test case for goodsReceivedNoteLinePATCHRequestGRNIDLinesLineIDUpdate
     *
     * Updates a line for a goods received note..
     *
     */
    public function testGoodsReceivedNoteLinePATCHRequestGRNIDLinesLineIDUpdate()
    {
    }

    /**
     * Test case for goodsReceivedNoteLinePOSTRequestGRNIDLinesPost
     *
     * Appends a line to a goods received note..
     *
     */
    public function testGoodsReceivedNoteLinePOSTRequestGRNIDLinesPost()
    {
    }

    /**
     * Test case for goodsReceivedNoteLinesGETManyRequestGRNIDLinesGet
     *
     * Retrieves a list of goods received note lines..
     *
     */
    public function testGoodsReceivedNoteLinesGETManyRequestGRNIDLinesGet()
    {
    }

    /**
     * Test case for goodsReceivedNotePATCHRequestGRNIDUpdate
     *
     * Updates a GRN..
     *
     */
    public function testGoodsReceivedNotePATCHRequestGRNIDUpdate()
    {
    }

    /**
     * Test case for goodsReceivedNotePOSTRequestPost
     *
     * Creates a GRN..
     *
     */
    public function testGoodsReceivedNotePOSTRequestPost()
    {
    }

    /**
     * Test case for goodsReceivedNotePurchaseOrderDELETERequestGRNIDPurchaseOrdersOrderIDDelete
     *
     * Deletes a purchase order from a goods received note..
     *
     */
    public function testGoodsReceivedNotePurchaseOrderDELETERequestGRNIDPurchaseOrdersOrderIDDelete()
    {
    }

    /**
     * Test case for goodsReceivedNotePurchaseOrderGETRequestGRNIDPurchaseOrdersOrderIDGet
     *
     * Retrieves a goods received note purchase order..
     *
     */
    public function testGoodsReceivedNotePurchaseOrderGETRequestGRNIDPurchaseOrdersOrderIDGet()
    {
    }

    /**
     * Test case for goodsReceivedNotePurchaseOrderPOSTRequestGRNIDPurchaseOrdersPost
     *
     * Appends a purchase order to a goods received note..
     *
     */
    public function testGoodsReceivedNotePurchaseOrderPOSTRequestGRNIDPurchaseOrdersPost()
    {
    }

    /**
     * Test case for goodsReceivedNotePurchaseOrdersGETManyRequestGRNIDPurchaseOrdersGet
     *
     * Retrieves a list of goods received note purchase orders..
     *
     */
    public function testGoodsReceivedNotePurchaseOrdersGETManyRequestGRNIDPurchaseOrdersGet()
    {
    }

    /**
     * Test case for goodsReceivedNoteSAVERequestSaveGet
     *
     * Saves a stateful stateful goods received note..
     *
     */
    public function testGoodsReceivedNoteSAVERequestSaveGet()
    {
    }
}
